// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RelisoftHR.Data;

#nullable disable

namespace RelisoftHR.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260713104345_SeedDemoUsers")]
    partial class SeedDemoUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RelisoftHR.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("JobRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PrimaryTeamId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SalaryStructureDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryTeamId");

                    b.HasIndex("RoleId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "HR",
                            Designation = "HR Lead",
                            Email = "preeti@relisoft.com",
                            EmployeeCode = "EMP-001",
                            EmploymentType = "Full-time",
                            FullName = "Preeti Sharma",
                            JobRole = "HR Lead",
                            JoinDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Mumbai",
                            RoleId = 7
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Management",
                            Designation = "CEO",
                            Email = "rakesh@relisoft.com",
                            EmployeeCode = "EMP-002",
                            EmploymentType = "Full-time",
                            FullName = "Rakesh Mehta",
                            JobRole = "CEO",
                            JoinDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Mumbai",
                            RoleId = 6
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "Software Engineer",
                            Email = "aradhana@relisoft.com",
                            EmployeeCode = "EMP-003",
                            EmploymentType = "Full-time",
                            FullName = "Aradhana Singh",
                            JobRole = "Software Engineer",
                            JoinDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Mumbai",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeDeviceTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedHrId")
                        .HasColumnType("int");

                    b.Property<string>("AssignedHrName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeDeviceTickets");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeDeviceTicketTimelineEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceTicketId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceTicketId");

                    b.ToTable("EmployeeDeviceTicketTimelineEvents");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeLeaveBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AllocatedLeaves")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("RemainingLeaves")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UsedLeaves")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("EmployeeId", "LeaveTypeId")
                        .IsUnique();

                    b.ToTable("EmployeeLeaveBalances");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeOnboardingDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExperienceCompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExperienceId")
                        .HasColumnType("int");

                    b.Property<int>("OnboardingProfileId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StoredFilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OnboardingProfileId");

                    b.ToTable("EmployeeOnboardingDocuments");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeOnboardingExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OnboardingProfileId")
                        .HasColumnType("int");

                    b.Property<bool>("RelievingEmailForwarded")
                        .HasColumnType("bit");

                    b.Property<decimal?>("YearsOfExperience")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OnboardingProfileId");

                    b.ToTable("EmployeeOnboardingExperiences");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeOnboardingProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AadhaarNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("HasPriorExperience")
                        .HasColumnType("bit");

                    b.Property<string>("PanNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeOnboardingProfiles");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("EmployeeId", "TeamId")
                        .IsUnique();

                    b.ToTable("EmployeeTeams");
                });

            modelBuilder.Entity("RelisoftHR.Models.HrPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowHalfDayLeave")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HrPolicies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowHalfDayLeave = false,
                            UpdatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("RelisoftHR.Models.LeaveApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActionedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AppliedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovalReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ApproverId")
                        .HasColumnType("int");

                    b.Property<string>("ApproverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CanCancel")
                        .HasColumnType("bit");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHalfDay")
                        .HasColumnType("bit");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalDays")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveApplications");
                });

            modelBuilder.Entity("RelisoftHR.Models.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LeaveTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Sick/Casual Leave",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Planned Leave",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Maternity Leave",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Paternity Leave",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Bereavement Leave",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Compensatory Off",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Marriage Leave",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Special Leave",
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("RelisoftHR.Models.OrganizationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseRoleId")
                        .HasColumnType("int");

                    b.Property<int>("Importance")
                        .HasColumnType("int");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("OrganizationRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseRoleId = 1,
                            Importance = 100,
                            IsCustom = false,
                            Name = "Employee"
                        },
                        new
                        {
                            Id = 2,
                            BaseRoleId = 1,
                            Importance = 200,
                            IsCustom = false,
                            Label = "Team Lead",
                            Name = "TeamLead"
                        },
                        new
                        {
                            Id = 3,
                            BaseRoleId = 3,
                            Importance = 300,
                            IsCustom = false,
                            Label = "HR L1",
                            Name = "HR"
                        },
                        new
                        {
                            Id = 4,
                            BaseRoleId = 1,
                            Importance = 150,
                            IsCustom = false,
                            Label = "Senior Software Engineer",
                            Name = "SeniorSoftwareEngineer"
                        },
                        new
                        {
                            Id = 5,
                            BaseRoleId = 5,
                            Importance = 400,
                            IsCustom = false,
                            Label = "Technical Manager L1",
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 6,
                            BaseRoleId = 5,
                            Importance = 600,
                            IsCustom = false,
                            Label = "Organization Head",
                            Name = "OrganizationHead"
                        },
                        new
                        {
                            Id = 7,
                            BaseRoleId = 3,
                            Importance = 500,
                            IsCustom = false,
                            Label = "HR L2",
                            Name = "HRL2"
                        },
                        new
                        {
                            Id = 8,
                            BaseRoleId = 5,
                            Importance = 450,
                            IsCustom = false,
                            Label = "Technical Manager L2",
                            Name = "ManagerL2"
                        },
                        new
                        {
                            Id = 9,
                            BaseRoleId = 9,
                            Importance = 700,
                            IsCustom = false,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 10,
                            BaseRoleId = 9,
                            Importance = 800,
                            IsCustom = false,
                            Label = "Super Admin",
                            Name = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("RelisoftHR.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("RelisoftHR.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeadId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("RelisoftHR.Models.UserLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserLogins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            PasswordHash = "$2a$11$1OmqZ7Lg1.9.5dC2qwF3He4EDiSghkDr94W1CrHjxUML9COevlnhy",
                            Username = "preeti"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 2,
                            PasswordHash = "$2a$11$1OmqZ7Lg1.9.5dC2qwF3He4EDiSghkDr94W1CrHjxUML9COevlnhy",
                            Username = "rakesh"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 3,
                            PasswordHash = "$2a$11$1OmqZ7Lg1.9.5dC2qwF3He4EDiSghkDr94W1CrHjxUML9COevlnhy",
                            Username = "aradhana"
                        });
                });

            modelBuilder.Entity("RelisoftHR.Models.Employee", b =>
                {
                    b.HasOne("RelisoftHR.Models.Team", "PrimaryTeam")
                        .WithMany()
                        .HasForeignKey("PrimaryTeamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RelisoftHR.Models.OrganizationRole", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryTeam");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeDeviceTicket", b =>
                {
                    b.HasOne("RelisoftHR.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeDeviceTicketTimelineEvent", b =>
                {
                    b.HasOne("RelisoftHR.Models.EmployeeDeviceTicket", "Ticket")
                        .WithMany("Timeline")
                        .HasForeignKey("DeviceTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeLeaveBalance", b =>
                {
                    b.HasOne("RelisoftHR.Models.Employee", "Employee")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RelisoftHR.Models.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeOnboardingDocument", b =>
                {
                    b.HasOne("RelisoftHR.Models.EmployeeOnboardingProfile", "Profile")
                        .WithMany("Documents")
                        .HasForeignKey("OnboardingProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeOnboardingExperience", b =>
                {
                    b.HasOne("RelisoftHR.Models.EmployeeOnboardingProfile", "Profile")
                        .WithMany("Experiences")
                        .HasForeignKey("OnboardingProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeOnboardingProfile", b =>
                {
                    b.HasOne("RelisoftHR.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeTeam", b =>
                {
                    b.HasOne("RelisoftHR.Models.Employee", "Employee")
                        .WithMany("EmployeeTeams")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RelisoftHR.Models.Team", "Team")
                        .WithMany("EmployeeTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("RelisoftHR.Models.LeaveApplication", b =>
                {
                    b.HasOne("RelisoftHR.Models.Employee", "Employee")
                        .WithMany("LeaveApplications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RelisoftHR.Models.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("RelisoftHR.Models.Team", b =>
                {
                    b.HasOne("RelisoftHR.Models.Employee", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RelisoftHR.Models.Project", "Project")
                        .WithMany("Teams")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("RelisoftHR.Models.UserLogin", b =>
                {
                    b.HasOne("RelisoftHR.Models.Employee", "Employee")
                        .WithOne("UserLogin")
                        .HasForeignKey("RelisoftHR.Models.UserLogin", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("RelisoftHR.Models.Employee", b =>
                {
                    b.Navigation("EmployeeTeams");

                    b.Navigation("LeaveApplications");

                    b.Navigation("LeaveBalances");

                    b.Navigation("UserLogin");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeDeviceTicket", b =>
                {
                    b.Navigation("Timeline");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeOnboardingProfile", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("RelisoftHR.Models.OrganizationRole", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("RelisoftHR.Models.Project", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("RelisoftHR.Models.Team", b =>
                {
                    b.Navigation("EmployeeTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
