// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RelisoftHR.Data;

#nullable disable

namespace RelisoftHR.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260713143331_UserLoginIsActive")]
    partial class UserLoginIsActive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RelisoftHR.Models.ApprovalDelegate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DelegateId")
                        .HasColumnType("int");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DelegateId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ManagerId", "ProjectId", "DelegateId")
                        .IsUnique();

                    b.ToTable("ApprovalDelegates");
                });

            modelBuilder.Entity("RelisoftHR.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("RelisoftHR.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("JobRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PrimaryTeamId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("SalaryStructureId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryTeamId");

                    b.HasIndex("RoleId");

                    b.HasIndex("SalaryStructureId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "HR",
                            Designation = "HR Lead",
                            Email = "preeti@relisoft.com",
                            EmployeeCode = "EMP-001",
                            EmploymentType = "Full-time",
                            FullName = "Preeti Patil",
                            JobRole = "HR Lead",
                            JoinDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Mumbai",
                            RoleId = 7,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Management",
                            Designation = "CEO",
                            Email = "rakesh@relisoft.com",
                            EmployeeCode = "EMP-002",
                            EmploymentType = "Full-time",
                            FullName = "Rakesh Patil",
                            JobRole = "CEO",
                            JoinDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Mumbai",
                            RoleId = 6,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "Software Engineer",
                            Email = "aradhana@relisoft.com",
                            EmployeeCode = "EMP-003",
                            EmploymentType = "Full-time",
                            FullName = "Aradhana Shinde",
                            JobRole = "Software Engineer",
                            JoinDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Mumbai",
                            RoleId = 1,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeAssets");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeLeaveBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AllocatedLeaves")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("RemainingLeaves")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UsedLeaves")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("EmployeeId", "LeaveTypeId")
                        .IsUnique();

                    b.ToTable("EmployeeLeaveBalances");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeOffboarding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssetsReturnedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EmailDeactivatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GatePassReturnedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IdDeactivatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastWorkingDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ResignationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("EmployeeOffboardings");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeOnboarding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClientIdCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompletedSteps")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GatePassIssuedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReliSoftIdCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VirtualIdCardIssuedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("EmployeeOnboardings");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeOnboardingDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExperienceCompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExperienceId")
                        .HasColumnType("int");

                    b.Property<int>("OnboardingProfileId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StoredFilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OnboardingProfileId");

                    b.ToTable("EmployeeOnboardingDocuments");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeOnboardingExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OnboardingProfileId")
                        .HasColumnType("int");

                    b.Property<bool>("RelievingEmailForwarded")
                        .HasColumnType("bit");

                    b.Property<decimal?>("YearsOfExperience")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OnboardingProfileId");

                    b.ToTable("EmployeeOnboardingExperiences");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeOnboardingProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AadhaarNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("HasPriorExperience")
                        .HasColumnType("bit");

                    b.Property<string>("PanNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeOnboardingProfiles");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeOnboardingStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChecklistItemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OnboardingId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistItemId");

                    b.HasIndex("OnboardingId");

                    b.ToTable("EmployeeOnboardingSteps");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("EmployeeId", "TeamId")
                        .IsUnique();

                    b.ToTable("EmployeeTeams");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedHrId")
                        .HasColumnType("int");

                    b.Property<string>("AssignedHrName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("ItemDetail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeTickets");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeTicketTimelineEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("EmployeeTicketTimelineEvents");
                });

            modelBuilder.Entity("RelisoftHR.Models.HrPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowHalfDayLeave")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HrPolicies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowHalfDayLeave = false,
                            UpdatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("RelisoftHR.Models.LeaveAccrualLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AccrualDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("AccruedDays")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveAccrualLogs");
                });

            modelBuilder.Entity("RelisoftHR.Models.LeaveApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActionedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AppliedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovalReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ApproverId")
                        .HasColumnType("int");

                    b.Property<string>("ApproverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CanCancel")
                        .HasColumnType("bit");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHalfDay")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMedicalLeave")
                        .HasColumnType("bit");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("LossOfPay")
                        .HasColumnType("bit");

                    b.Property<string>("MedicalCertificatePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalDays")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveApplications");
                });

            modelBuilder.Entity("RelisoftHR.Models.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CarryForwardPct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CompOffValidityDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompOff")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFloaterHoliday")
                        .HasColumnType("bit");

                    b.Property<int>("MaxFloaterPerYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LeaveTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarryForwardPct = 0m,
                            CompOffValidityDays = 0,
                            IsActive = true,
                            IsCompOff = false,
                            IsFloaterHoliday = false,
                            MaxFloaterPerYear = 0,
                            Name = "Sick/Casual Leave",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CarryForwardPct = 50m,
                            CompOffValidityDays = 0,
                            IsActive = true,
                            IsCompOff = false,
                            IsFloaterHoliday = false,
                            MaxFloaterPerYear = 0,
                            Name = "Planned Leave",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CarryForwardPct = 0m,
                            CompOffValidityDays = 0,
                            IsActive = true,
                            IsCompOff = false,
                            IsFloaterHoliday = false,
                            MaxFloaterPerYear = 0,
                            Name = "Maternity Leave",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CarryForwardPct = 0m,
                            CompOffValidityDays = 0,
                            IsActive = true,
                            IsCompOff = false,
                            IsFloaterHoliday = false,
                            MaxFloaterPerYear = 0,
                            Name = "Paternity Leave",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CarryForwardPct = 0m,
                            CompOffValidityDays = 0,
                            IsActive = true,
                            IsCompOff = false,
                            IsFloaterHoliday = false,
                            MaxFloaterPerYear = 0,
                            Name = "Bereavement Leave",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            CarryForwardPct = 0m,
                            CompOffValidityDays = 30,
                            IsActive = true,
                            IsCompOff = true,
                            IsFloaterHoliday = false,
                            MaxFloaterPerYear = 0,
                            Name = "Compensatory Off",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            CarryForwardPct = 0m,
                            CompOffValidityDays = 0,
                            IsActive = true,
                            IsCompOff = false,
                            IsFloaterHoliday = false,
                            MaxFloaterPerYear = 0,
                            Name = "Marriage Leave",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            CarryForwardPct = 0m,
                            CompOffValidityDays = 0,
                            IsActive = true,
                            IsCompOff = false,
                            IsFloaterHoliday = false,
                            MaxFloaterPerYear = 0,
                            Name = "Special Leave",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            CarryForwardPct = 0m,
                            CompOffValidityDays = 0,
                            IsActive = true,
                            IsCompOff = false,
                            IsFloaterHoliday = true,
                            MaxFloaterPerYear = 2,
                            Name = "Floater Holiday",
                            SortOrder = 9
                        });
                });

            modelBuilder.Entity("RelisoftHR.Models.OnboardingChecklistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OnboardingChecklistItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create ReliSoft email and system account",
                            IsActive = true,
                            IsMandatory = true,
                            Name = "ReliSoft ID Creation",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create client-specific system accounts",
                            IsActive = true,
                            IsMandatory = true,
                            Name = "Client ID Creation",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Generate virtual employee ID card",
                            IsActive = true,
                            IsMandatory = true,
                            Name = "Virtual ID Card",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Issue gate entry pass",
                            IsActive = true,
                            IsMandatory = true,
                            Name = "Gate Pass",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Assign laptop, monitor and other hardware",
                            IsActive = true,
                            IsMandatory = true,
                            Name = "Asset Allocation",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Distribute welcome kit and documentation",
                            IsActive = true,
                            IsMandatory = true,
                            Name = "Welcome Kit",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("RelisoftHR.Models.OrganizationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseRoleId")
                        .HasColumnType("int");

                    b.Property<int>("Importance")
                        .HasColumnType("int");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("OrganizationRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseRoleId = 1,
                            Importance = 100,
                            IsCustom = false,
                            Name = "Employee"
                        },
                        new
                        {
                            Id = 2,
                            BaseRoleId = 1,
                            Importance = 200,
                            IsCustom = false,
                            Label = "Team Lead",
                            Name = "TeamLead"
                        },
                        new
                        {
                            Id = 3,
                            BaseRoleId = 3,
                            Importance = 300,
                            IsCustom = false,
                            Label = "HR L1",
                            Name = "HR"
                        },
                        new
                        {
                            Id = 4,
                            BaseRoleId = 1,
                            Importance = 150,
                            IsCustom = false,
                            Label = "Senior Software Engineer",
                            Name = "SeniorSoftwareEngineer"
                        },
                        new
                        {
                            Id = 5,
                            BaseRoleId = 5,
                            Importance = 400,
                            IsCustom = false,
                            Label = "Technical Manager L1",
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 6,
                            BaseRoleId = 5,
                            Importance = 600,
                            IsCustom = false,
                            Label = "Organization Head",
                            Name = "OrganizationHead"
                        },
                        new
                        {
                            Id = 7,
                            BaseRoleId = 3,
                            Importance = 500,
                            IsCustom = false,
                            Label = "HR L2",
                            Name = "HRL2"
                        },
                        new
                        {
                            Id = 8,
                            BaseRoleId = 5,
                            Importance = 450,
                            IsCustom = false,
                            Label = "Technical Manager L2",
                            Name = "ManagerL2"
                        },
                        new
                        {
                            Id = 9,
                            BaseRoleId = 9,
                            Importance = 700,
                            IsCustom = false,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 10,
                            BaseRoleId = 9,
                            Importance = 800,
                            IsCustom = false,
                            Label = "Super Admin",
                            Name = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("RelisoftHR.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("RelisoftHR.Models.SalaryStructure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("FixedPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Gratuity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Insurance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherDeductions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PF")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VariablePay")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("SalaryStructures");
                });

            modelBuilder.Entity("RelisoftHR.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeadId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("RelisoftHR.Models.UserLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserLogins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            IsActive = true,
                            PasswordHash = "$2a$11$1OmqZ7Lg1.9.5dC2qwF3He4EDiSghkDr94W1CrHjxUML9COevlnhy",
                            Username = "preeti"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 2,
                            IsActive = true,
                            PasswordHash = "$2a$11$1OmqZ7Lg1.9.5dC2qwF3He4EDiSghkDr94W1CrHjxUML9COevlnhy",
                            Username = "rakesh"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 3,
                            IsActive = true,
                            PasswordHash = "$2a$11$1OmqZ7Lg1.9.5dC2qwF3He4EDiSghkDr94W1CrHjxUML9COevlnhy",
                            Username = "aradhana"
                        });
                });

            modelBuilder.Entity("RelisoftHR.Models.ApprovalDelegate", b =>
                {
                    b.HasOne("RelisoftHR.Models.Employee", "Delegate")
                        .WithMany()
                        .HasForeignKey("DelegateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RelisoftHR.Models.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RelisoftHR.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delegate");

                    b.Navigation("Manager");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("RelisoftHR.Models.Employee", b =>
                {
                    b.HasOne("RelisoftHR.Models.Team", "PrimaryTeam")
                        .WithMany()
                        .HasForeignKey("PrimaryTeamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RelisoftHR.Models.OrganizationRole", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RelisoftHR.Models.SalaryStructure", "SalaryStructure")
                        .WithMany()
                        .HasForeignKey("SalaryStructureId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("PrimaryTeam");

                    b.Navigation("Role");

                    b.Navigation("SalaryStructure");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeAsset", b =>
                {
                    b.HasOne("RelisoftHR.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RelisoftHR.Models.Employee", "Employee")
                        .WithMany("Assets")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeLeaveBalance", b =>
                {
                    b.HasOne("RelisoftHR.Models.Employee", "Employee")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RelisoftHR.Models.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeOffboarding", b =>
                {
                    b.HasOne("RelisoftHR.Models.Employee", "Employee")
                        .WithOne("Offboarding")
                        .HasForeignKey("RelisoftHR.Models.EmployeeOffboarding", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeOnboarding", b =>
                {
                    b.HasOne("RelisoftHR.Models.Employee", "Employee")
                        .WithOne("Onboarding")
                        .HasForeignKey("RelisoftHR.Models.EmployeeOnboarding", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeOnboardingDocument", b =>
                {
                    b.HasOne("RelisoftHR.Models.EmployeeOnboardingProfile", "Profile")
                        .WithMany("Documents")
                        .HasForeignKey("OnboardingProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeOnboardingExperience", b =>
                {
                    b.HasOne("RelisoftHR.Models.EmployeeOnboardingProfile", "Profile")
                        .WithMany("Experiences")
                        .HasForeignKey("OnboardingProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeOnboardingProfile", b =>
                {
                    b.HasOne("RelisoftHR.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeOnboardingStep", b =>
                {
                    b.HasOne("RelisoftHR.Models.OnboardingChecklistItem", "ChecklistItem")
                        .WithMany()
                        .HasForeignKey("ChecklistItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RelisoftHR.Models.EmployeeOnboarding", "Onboarding")
                        .WithMany("Steps")
                        .HasForeignKey("OnboardingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistItem");

                    b.Navigation("Onboarding");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeTeam", b =>
                {
                    b.HasOne("RelisoftHR.Models.Employee", "Employee")
                        .WithMany("EmployeeTeams")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RelisoftHR.Models.Team", "Team")
                        .WithMany("EmployeeTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeTicket", b =>
                {
                    b.HasOne("RelisoftHR.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeTicketTimelineEvent", b =>
                {
                    b.HasOne("RelisoftHR.Models.EmployeeTicket", "Ticket")
                        .WithMany("Timeline")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("RelisoftHR.Models.LeaveAccrualLog", b =>
                {
                    b.HasOne("RelisoftHR.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RelisoftHR.Models.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("RelisoftHR.Models.LeaveApplication", b =>
                {
                    b.HasOne("RelisoftHR.Models.Employee", "Employee")
                        .WithMany("LeaveApplications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RelisoftHR.Models.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("RelisoftHR.Models.SalaryStructure", b =>
                {
                    b.HasOne("RelisoftHR.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("RelisoftHR.Models.Team", b =>
                {
                    b.HasOne("RelisoftHR.Models.Employee", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RelisoftHR.Models.Project", "Project")
                        .WithMany("Teams")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("RelisoftHR.Models.UserLogin", b =>
                {
                    b.HasOne("RelisoftHR.Models.Employee", "Employee")
                        .WithOne("UserLogin")
                        .HasForeignKey("RelisoftHR.Models.UserLogin", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("RelisoftHR.Models.Employee", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("EmployeeTeams");

                    b.Navigation("LeaveApplications");

                    b.Navigation("LeaveBalances");

                    b.Navigation("Offboarding");

                    b.Navigation("Onboarding");

                    b.Navigation("UserLogin");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeOnboarding", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeOnboardingProfile", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("RelisoftHR.Models.EmployeeTicket", b =>
                {
                    b.Navigation("Timeline");
                });

            modelBuilder.Entity("RelisoftHR.Models.OrganizationRole", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("RelisoftHR.Models.Project", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("RelisoftHR.Models.Team", b =>
                {
                    b.Navigation("EmployeeTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
