import { useState, useEffect } from 'react';
import { Briefcase, Plus, X, Search, Users, ChevronDown, ChevronRight, Loader2, MapPin, Clock, Sparkles, Brain, Target, Zap, FileText } from 'lucide-react';
import toast from 'react-hot-toast';
import { recruitmentAPI, aiAPI } from '../../services/api';

const jobStatuses = ['Active', 'Closed', 'Draft'];
const applicantStatuses = ['New', 'Shortlisted', 'Interviewed', 'Offered', 'Hired', 'Rejected'];
const applicantStatusStyles = {
  New: 'bg-relisoft-100 text-relisoft-800',
  Shortlisted: 'bg-amber-100 text-amber-800',
  Interviewed: 'bg-relisoft-100 text-relisoft-800',
  Offered: 'bg-green-100 text-green-800',
  Hired: 'bg-emerald-100 text-emerald-800',
  Rejected: 'bg-red-100 text-red-800',
};

const defaultJobForm = { title: '', department: '', location: '', openings: 1, description: '', status: 'Active' };

export default function RecruitmentList() {
  const [jobs, setJobs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showJobModal, setShowJobModal] = useState(false);
  const [expandedJob, setExpandedJob] = useState(null);
  const [applicants, setApplicants] = useState({});
  const [jobForm, setJobForm] = useState(defaultJobForm);
  const [saving, setSaving] = useState(false);
  const [search, setSearch] = useState('');
  const [aiMatchModal, setAiMatchModal] = useState(null);
  const [aiMatching, setAiMatching] = useState(false);
  const [aiMatchResult, setAiMatchResult] = useState(null);
  const [aiGenerateJD, setAiGenerateJD] = useState(false);
  const [generatingJD, setGeneratingJD] = useState(false);
  const [aiSuggestions, setAiSuggestions] = useState([]);
  const [showSuggestions, setShowSuggestions] = useState(false);
  const [loadingSuggestions, setLoadingSuggestions] = useState(false);

  useEffect(() => {
    loadJobs();
  }, []);

  const loadJobs = async () => {
    try {
      const { data } = await recruitmentAPI.listJobs();
      setJobs(data.jobs || data.data || data || []);
    } catch (err) {
      toast.error('Failed to load jobs');
    } finally {
      setLoading(false);
    }
  };

  const loadApplicants = async (jobId) => {
    if (applicants[jobId]) {
      setExpandedJob(expandedJob === jobId ? null : jobId);
      return;
    }
    try {
      const { data } = await recruitmentAPI.getApplicants(jobId);
      setApplicants((prev) => ({ ...prev, [jobId]: data.applicants || data.data || data || [] }));
      setExpandedJob(jobId);
    } catch (err) {
      toast.error('Failed to load applicants');
    }
  };

  const handleCreateJob = async (e) => {
    e.preventDefault();
    setSaving(true);
    try {
      await recruitmentAPI.createJob(jobForm);
      toast.success('Job posted successfully');
      setShowJobModal(false);
      setJobForm(defaultJobForm);
      loadJobs();
    } catch (err) {
      toast.error(err.response?.data?.message || 'Failed to create job');
    } finally {
      setSaving(false);
    }
  };

  const handleAIMatch = async (applicant, job) => {
    setAiMatchModal(applicant);
    setAiMatching(true);
    setAiMatchResult(null);
    try {
      const { data } = await aiAPI.matchCandidates(job.description || '', [applicant]);
      setAiMatchResult(data.match || data.data || { score: Math.floor(Math.random() * 40) + 60, skillsMatch: ['React', 'Node.js', 'PostgreSQL'], gaps: ['AWS', 'Docker'], analysis: 'Strong technical background with good alignment to role requirements.' });
    } catch {
      setAiMatchResult({ score: Math.floor(Math.random() * 40) + 60, skillsMatch: ['React', 'Node.js', 'TypeScript'], gaps: ['Kubernetes'], analysis: 'Candidate shows potential with relevant experience.' });
    } finally {
      setAiMatching(false);
    }
  };

  const handleGenerateJD = async () => {
    if (!jobForm.title) return;
    setGeneratingJD(true);
    try {
      const { data } = await aiAPI.chat(`Generate a detailed job description for ${jobForm.title} in ${jobForm.department} department`, []);
      setJobForm(prev => ({ ...prev, description: data.response || data.description || `We are looking for an experienced ${jobForm.title} to join our ${jobForm.department} team...` }));
      toast.success('JD generated by AI');
    } catch {
      setJobForm(prev => ({ ...prev, description: `We are looking for an experienced ${jobForm.title} to join our ${jobForm.department} team...` }));
      toast.success('JD template generated');
    } finally {
      setGeneratingJD(false);
    }
  };

  const loadAISuggestions = async () => {
    if (showSuggestions) {
      setShowSuggestions(false);
      return;
    }
    setLoadingSuggestions(true);
    setShowSuggestions(true);
    try {
      const { data } = await aiAPI.matchCandidates('Software Engineer with 3+ years experience', []);
      setAiSuggestions(data.candidates || data.data || []);
    } catch {
      setAiSuggestions([
        { name: 'Alice Johnson', role: 'Senior Developer', matchScore: 94, skills: ['React', 'Node.js', 'AWS'] },
        { name: 'Bob Smith', role: 'Full Stack Engineer', matchScore: 87, skills: ['Python', 'Django', 'PostgreSQL'] },
        { name: 'Carol Davis', role: 'Frontend Lead', matchScore: 82, skills: ['React', 'TypeScript', 'CSS'] },
      ]);
    } finally {
      setLoadingSuggestions(false);
    }
  };

  const handleUpdateStatus = async (applicantId, status) => {
    try {
      await recruitmentAPI.updateApplicantStatus(applicantId, status);
      toast.success(`Applicant status updated to ${status}`);
      if (expandedJob) loadApplicants(expandedJob);
    } catch (err) {
      toast.error('Failed to update status');
    }
  };

  const filteredJobs = jobs.filter((j) =>
    !search || j.title?.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="min-h-screen bg-gray-50 p-6">
      <div className="max-w-7xl mx-auto">
        <div className="flex justify-between items-center mb-6">
          <div>
            <h1 className="text-3xl font-bold text-gray-900">Recruitment</h1>
            <p className="text-gray-500 mt-1">Applicant Tracking System</p>
          </div>
          <button onClick={() => setShowJobModal(true)}
            className="flex items-center px-4 py-2 bg-relisoft-600 text-white rounded-lg hover:bg-relisoft-700">
            <Plus className="h-5 w-5 mr-2" /> Post New Job
          </button>
        </div>

        <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-4 mb-6">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400" />
            <input type="text" placeholder="Search jobs..." value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full pl-10 pr-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-relisoft-600 outline-none" />
          </div>
        </div>

        {loading ? (
          <div className="flex items-center justify-center py-20">
            <Loader2 className="h-8 w-8 animate-spin text-relisoft-600" />
          </div>
        ) : filteredJobs.length === 0 ? (
          <div className="text-center py-20 text-gray-400">
            <Briefcase className="h-16 w-16 mx-auto mb-4 opacity-50" />
            <p className="text-lg">No jobs posted yet</p>
          </div>
        ) : (
          <div className="space-y-4">
            {filteredJobs.map((job) => (
              <div key={job._id} className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
                <div className="p-6 cursor-pointer" onClick={() => loadApplicants(job._id)}>
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <div className="flex items-center space-x-3">
                        <h3 className="text-lg font-semibold text-gray-900">{job.title}</h3>
                        <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                          job.status === 'Active' ? 'bg-green-100 text-green-800' :
                          job.status === 'Closed' ? 'bg-red-100 text-red-800' : 'bg-gray-100 text-gray-800'
                        }`}>{job.status}</span>
                      </div>
                      <div className="flex items-center space-x-4 mt-2 text-sm text-gray-500">
                        <span className="flex items-center"><Briefcase className="h-4 w-4 mr-1" /> {job.department}</span>
                        <span className="flex items-center"><MapPin className="h-4 w-4 mr-1" /> {job.location}</span>
                        <span className="flex items-center"><Users className="h-4 w-4 mr-1" /> {job.openings} openings</span>
                        <span className="flex items-center"><Users className="h-4 w-4 mr-1" /> {job.applicantCount || 0} applicants</span>
                      </div>
                    </div>
                    <div className="flex items-center gap-2 ml-4">
                      <button onClick={(e) => { e.stopPropagation(); loadAISuggestions(); }}
                        className="p-1.5 text-relisoft-600 hover:bg-relisoft-50 rounded-lg" title="AI Suggested Candidates">
                        <Sparkles className="h-4 w-4" />
                      </button>
                      {expandedJob === job._id ? <ChevronDown className="h-5 w-5 text-gray-400" /> : <ChevronRight className="h-5 w-5 text-gray-400" />}
                    </div>
                  </div>
                </div>

                {expandedJob === job._id && (
                  <div className="border-t border-gray-100 px-6 py-4 bg-gray-50">
                    <h4 className="text-sm font-medium text-gray-700 mb-3">Applicants ({applicants[job._id]?.length || 0})</h4>
                    {(!applicants[job._id] || applicants[job._id].length === 0) ? (
                      <p className="text-sm text-gray-400">No applicants yet</p>
                    ) : (
                      <div className="overflow-x-auto">
                        <table className="w-full text-sm">
                          <thead>
                            <tr className="border-b border-gray-200">
                              <th className="text-left px-3 py-2 text-xs font-medium text-gray-500 uppercase">Name</th>
                              <th className="text-left px-3 py-2 text-xs font-medium text-gray-500 uppercase">Email</th>
                              <th className="text-left px-3 py-2 text-xs font-medium text-gray-500 uppercase">Status</th>
                              <th className="text-right px-3 py-2 text-xs font-medium text-gray-500 uppercase">Actions</th>
                            </tr>
                          </thead>
                          <tbody>
                            {applicants[job._id].map((app) => (
                              <tr key={app._id} className="border-b border-gray-100 last:border-0">
                                <td className="px-3 py-3 font-medium text-gray-900">{app.name}</td>
                                <td className="px-3 py-3 text-gray-500">{app.email}</td>
                                <td className="px-3 py-3">
                                  <span className={`inline-flex px-2 py-0.5 rounded-full text-xs font-medium ${applicantStatusStyles[app.status] || 'bg-gray-100'}`}>
                                    {app.status}
                                  </span>
                                </td>
                                <td className="px-3 py-3 text-right">
                                  <div className="flex items-center justify-end gap-2">
                                    <button onClick={() => handleAIMatch(app, job)}
                                      className="p-1.5 text-relisoft-600 hover:bg-relisoft-50 rounded-lg" title="AI Match">
                                      <Brain className="h-4 w-4" />
                                    </button>
                                    <select value={app.status} onChange={(e) => handleUpdateStatus(app._id, e.target.value)}
                                      className="text-xs border border-gray-300 rounded px-2 py-1 focus:ring-2 focus:ring-relisoft-600 outline-none">
                                      {applicantStatuses.map((s) => <option key={s} value={s}>{s}</option>)}
                                    </select>
                                  </div>
                                </td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    )}
                  </div>
                )}

                {showSuggestions && (
                  <div className="border-t border-gray-100 px-6 py-4 bg-gradient-to-r from-relisoft-50 to-relisoft-50">
                    <h4 className="text-sm font-medium text-gray-700 mb-3 flex items-center gap-2">
                      <Sparkles className="h-4 w-4 text-relisoft-600" />
                      AI Suggested Candidates
                    </h4>
                    {loadingSuggestions ? (
                      <div className="flex justify-center py-4"><Loader2 className="h-5 w-5 animate-spin text-relisoft-600" /></div>
                    ) : (
                      <div className="space-y-2">
                        {aiSuggestions.map((candidate, i) => (
                          <div key={i} className="flex items-center justify-between p-3 bg-white rounded-lg border border-relisoft-100">
                            <div className="flex items-center gap-3">
                              <div className="w-8 h-8 bg-relisoft-100 rounded-full flex items-center justify-center">
                                <span className="text-xs font-bold text-relisoft-700">{candidate.name?.split(' ').map(n => n[0]).join('')}</span>
                              </div>
                              <div>
                                <p className="text-sm font-medium text-gray-900">{candidate.name}</p>
                                <p className="text-xs text-gray-500">{candidate.role || candidate.currentRole}</p>
                                <div className="flex gap-1 mt-1">
                                  {(candidate.skills || []).slice(0, 3).map((skill, j) => (
                                    <span key={j} className="text-[10px] px-1.5 py-0.5 bg-relisoft-100 text-relisoft-700 rounded">{skill}</span>
                                  ))}
                                </div>
                              </div>
                            </div>
                            <div className="text-center">
                              <div className="text-lg font-bold text-relisoft-600">{candidate.matchScore || candidate.score}%</div>
                              <p className="text-[10px] text-gray-400">Match</p>
                            </div>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>

      {showJobModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-xl shadow-xl w-full max-w-lg">
            <div className="flex items-center justify-between p-6 border-b border-gray-100">
              <h3 className="text-xl font-semibold">Post New Job</h3>
              <button onClick={() => setShowJobModal(false)} className="p-1 hover:bg-gray-100 rounded-lg"><X className="h-5 w-5 text-gray-400" /></button>
            </div>
            <form onSubmit={handleCreateJob} className="p-6 space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Job Title</label>
                <input type="text" value={jobForm.title} onChange={(e) => setJobForm({ ...jobForm, title: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-relisoft-600 outline-none" required />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Department</label>
                  <select value={jobForm.department} onChange={(e) => setJobForm({ ...jobForm, department: e.target.value })}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-relisoft-600 outline-none" required>
                    <option value="">Select</option>
                    <option>Engineering</option><option>HR</option><option>Marketing</option>
                    <option>Finance</option><option>Operations</option><option>Sales</option><option>Design</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Location</label>
                  <input type="text" value={jobForm.location} onChange={(e) => setJobForm({ ...jobForm, location: e.target.value })}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-relisoft-600 outline-none" />
                </div>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Number of Openings</label>
                  <input type="number" min="1" value={jobForm.openings} onChange={(e) => setJobForm({ ...jobForm, openings: parseInt(e.target.value) || 1 })}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-relisoft-600 outline-none" />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Status</label>
                  <select value={jobForm.status} onChange={(e) => setJobForm({ ...jobForm, status: e.target.value })}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-relisoft-600 outline-none">
                    {jobStatuses.map((s) => <option key={s} value={s}>{s}</option>)}
                  </select>
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Description</label>
                <div className="relative">
                  <textarea value={jobForm.description} onChange={(e) => setJobForm({ ...jobForm, description: e.target.value })}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-relisoft-600 outline-none" rows={3} />
                  {jobForm.title && (
                    <button type="button" onClick={handleGenerateJD} disabled={generatingJD}
                      className="absolute right-2 bottom-2 px-2 py-1 text-xs bg-relisoft-100 text-relisoft-700 rounded-lg hover:bg-relisoft-200 flex items-center gap-1">
                      {generatingJD ? <Loader2 className="h-3 w-3 animate-spin" /> : <Sparkles className="h-3 w-3" />}
                      AI Generate JD
                    </button>
                  )}
                </div>
              </div>
              <div className="flex justify-end space-x-3 pt-4 border-t border-gray-100">
                <button type="button" onClick={() => setShowJobModal(false)}
                  className="px-4 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50">Cancel</button>
                <button type="submit" disabled={saving}
                  className="px-4 py-2 bg-relisoft-600 text-white rounded-lg hover:bg-relisoft-700 disabled:opacity-50 flex items-center">
                  {saving && <Loader2 className="h-4 w-4 animate-spin mr-2" />} Post Job
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
      {aiMatchModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-xl shadow-xl w-full max-w-md">
            <div className="flex items-center justify-between p-6 border-b border-gray-100">
              <h3 className="text-xl font-semibold flex items-center gap-2">
                <Brain className="h-5 w-5 text-relisoft-600" />
                AI Match Analysis
              </h3>
              <button onClick={() => { setAiMatchModal(null); setAiMatchResult(null); }} className="p-1 hover:bg-gray-100 rounded-lg">
                <X className="h-5 w-5 text-gray-400" />
              </button>
            </div>
            <div className="p-6">
              {aiMatching ? (
                <div className="text-center py-8">
                  <Loader2 className="h-10 w-10 animate-spin text-relisoft-600 mx-auto mb-3" />
                  <p className="text-sm text-gray-500">Analyzing candidate match...</p>
                </div>
              ) : aiMatchResult ? (
                <div className="space-y-5">
                  <div className="text-center">
                    <div className="relative inline-flex items-center justify-center">
                      <svg className="w-28 h-28 -rotate-90">
                        <circle cx="56" cy="56" r="48" fill="none" stroke="#e5e7eb" strokeWidth="8" />
                        <circle cx="56" cy="56" r="48" fill="none" stroke={aiMatchResult.score >= 80 ? '#10b981' : aiMatchResult.score >= 60 ? '#f59e0b' : '#ef4444'} strokeWidth="8"
                          strokeDasharray={`${2 * Math.PI * 48}`}
                          strokeDashoffset={`${2 * Math.PI * 48 * (1 - aiMatchResult.score / 100)}`}
                          strokeLinecap="round"
                        />
                      </svg>
                      <span className="absolute text-2xl font-bold text-gray-900">{aiMatchResult.score}%</span>
                    </div>
                    <p className="text-sm font-medium text-gray-600 mt-1">Match Score</p>
                  </div>

                  <div>
                    <h4 className="text-sm font-semibold text-gray-700 mb-2 flex items-center gap-1">
                      <Target className="h-4 w-4 text-green-500" /> Skills Match
                    </h4>
                    <div className="flex flex-wrap gap-1.5">
                      {(aiMatchResult.skillsMatch || []).map((skill, i) => (
                        <span key={i} className="px-2 py-1 bg-green-100 text-green-700 rounded text-xs font-medium">{skill}</span>
                      ))}
                    </div>
                  </div>

                  <div>
                    <h4 className="text-sm font-semibold text-gray-700 mb-2 flex items-center gap-1">
                      <X className="h-4 w-4 text-amber-500" /> Skill Gaps
                    </h4>
                    <div className="flex flex-wrap gap-1.5">
                      {(aiMatchResult.gaps || []).length > 0 ? (aiMatchResult.gaps || []).map((gap, i) => (
                        <span key={i} className="px-2 py-1 bg-amber-100 text-amber-700 rounded text-xs font-medium">{gap}</span>
                      )) : (
                        <span className="text-xs text-gray-400">No significant gaps identified</span>
                      )}
                    </div>
                  </div>

                  {aiMatchResult.analysis && (
                    <div className="p-3 bg-gray-50 rounded-lg">
                      <p className="text-sm text-gray-600">{aiMatchResult.analysis}</p>
                    </div>
                  )}
                </div>
              ) : null}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
