import { useEffect, useState } from 'react'
import useStore from '../store'
import {
  getSalaryDiscussions, createSalaryDiscussion, approveSalary, rejectSalary,
  getDocumentTemplates, createDocumentTemplate, getEmployeeDocuments,
  generateDocument, markDocumentSent, autoGenerateDocuments
} from '../api'

export default function HrDocsSalary() {
  const { setMessage, data, currentUser } = useStore()
  const [tab, setTab] = useState('salary')
  const [discussions, setDiscussions] = useState([])
  const [docs, setDocs] = useState([])
  const [templates, setTemplates] = useState([])
  const [selEmp, setSelEmp] = useState('')

  const [salForm, setSalForm] = useState({ employeeId: '', proposedSalary: '', notes: '' })
  const [templateForm, setTemplateForm] = useState({ name: '', documentType: 'OfferLetter', description: '', templateContent: '' })

  useEffect(() => { refresh() }, [])

  const refresh = async () => {
    try { setDiscussions(await getSalaryDiscussions()) } catch {}
    try { setTemplates(await getDocumentTemplates()) } catch {}
  }

  const refreshDocs = async () => {
    if (!selEmp) return
    try { setDocs(await getEmployeeDocuments(Number(selEmp))) } catch {}
  }

  useEffect(() => { refreshDocs() }, [selEmp])

  const handleCreateSalary = async () => {
    if (!salForm.employeeId || !salForm.proposedSalary) return
    await createSalaryDiscussion({
      employeeId: Number(salForm.employeeId),
      proposedSalary: Number(salForm.proposedSalary),
      proposedById: currentUser?.employeeId,
      notes: salForm.notes
    })
    setMessage({ type: 'success', text: 'Salary discussion created.' })
    setSalForm({ employeeId: '', proposedSalary: '', notes: '' })
    refresh()
  }

  const handleApprove = async (id, salary) => {
    await approveSalary(id, { approvedSalary: Number(salary), approvedById: currentUser?.employeeId })
    setMessage({ type: 'success', text: 'Salary approved.' }); refresh()
  }

  const handleReject = async (id) => {
    await rejectSalary(id); setMessage({ type: 'success', text: 'Salary proposal rejected.' }); refresh()
  }

  const handleCreateTemplate = async () => {
    if (!templateForm.name) return
    await createDocumentTemplate(templateForm)
    setTemplateForm({ name: '', documentType: 'OfferLetter', description: '', templateContent: '' })
    try { setTemplates(await getDocumentTemplates()) } catch {}
  }

  const handleGenerate = async (type) => {
    if (!selEmp) return
    await generateDocument(Number(selEmp), type)
    setMessage({ type: 'success', text: `${type} generated.` })
    refreshDocs()
  }

  const handleAutoGenerate = async () => {
    if (!selEmp) return
    const res = await autoGenerateDocuments(Number(selEmp))
    setMessage({ type: 'success', text: res.message })
    refreshDocs()
  }

  return (
    <div className="space-y-4">
      <div className="card-surface">
        <div className="p-5">
          <h2 className="font-heading font-bold text-xl text-navy dark:text-white">Salary discussions & documentation</h2>
          <p className="text-muted dark:text-white/60 text-sm mt-1">Propose and approve salaries, auto-generate offer letters, joining letters, Form 16, and more.</p>
        </div>
      </div>
      <div className="card-surface">
        <div className="p-5 flex items-center gap-3 border-b border-navy/10">
          {['salary', 'docs', 'templates'].map((t) => (
            <button key={t} onClick={() => setTab(t)} className={`px-5 py-2 rounded-xl text-xs font-bold transition-all ${tab === t ? 'bg-gradient-to-r from-gold-1 to-gold-2 text-navy-dark' : 'border border-navy/10 dark:border-white/10 text-navy/70 dark:text-white/70'}`}>
              {t === 'salary' ? 'Salary discussions' : t === 'docs' ? 'Documents' : 'Templates'}
            </button>
          ))}
        </div>

        {tab === 'salary' && (
          <div className="p-5 space-y-4">
            <div className="grid md:grid-cols-4 gap-3 p-4 rounded-xl border border-navy/10 dark:border-white/10 bg-amber-50/30">
              <select value={salForm.employeeId} onChange={(e) => setSalForm((s) => ({ ...s, employeeId: e.target.value }))} className="input">
                <option value="">Select employee...</option>
                {data.employees.filter((e) => e.status === 'Active' || e.status === 'Onboarding').map((e) => (<option key={e.id} value={e.id}>{e.fullName}</option>))}
              </select>
              <input type="number" value={salForm.proposedSalary} onChange={(e) => setSalForm((s) => ({ ...s, proposedSalary: e.target.value }))} className="input" placeholder="Proposed salary (₹)" />
              <input value={salForm.notes} onChange={(e) => setSalForm((s) => ({ ...s, notes: e.target.value }))} className="input" placeholder="Notes" />
              <button onClick={handleCreateSalary} className="px-4 py-2 bg-gradient-to-r from-gold-1 to-gold-2 text-navy-dark font-bold text-xs rounded-xl">Propose salary</button>
            </div>
            <div className="space-y-2">
              {discussions.map((d) => (
                <div key={d.id} className="p-4 rounded-xl border border-navy/10 dark:border-white/10 bg-white dark:bg-[var(--bg-secondary)] flex items-center justify-between">
                  <div>
                    <span className="font-bold text-navy dark:text-white text-sm">{d.employeeName}</span>
                    <span className="text-xs text-navy/50 dark:text-white/50 ml-3">Proposed: ₹{Number(d.proposedSalary).toLocaleString()}</span>
                    {d.approvedSalary && <span className="text-xs text-emerald-600 ml-3">Approved: ₹{Number(d.approvedSalary).toLocaleString()}</span>}
                    <span className={`ml-3 text-[10px] px-2 py-0.5 rounded font-bold ${
                      d.status === 'Proposed' ? 'bg-amber-50 dark:bg-amber-900/30 text-amber-700' :
                      d.status === 'Approved' ? 'bg-emerald-50 dark:bg-emerald-900/30 text-emerald-700' : 'bg-red-50 dark:bg-red-900/30 text-red-700'
                    }`}>{d.status}</span>
                    <div className="text-xs text-navy/50 dark:text-white/50 mt-1">{new Date(d.discussionDate).toLocaleDateString()}</div>
                  </div>
                  {d.status === 'Proposed' && (
                    <div className="flex gap-2">
                      <input type="number" placeholder="Approved ₹" className="input w-32" onBlur={(e) => handleApprove(d.id, e.target.value)} />
                      <button onClick={() => handleReject(d.id)} className="px-3 py-1.5 border border-red-200 text-red-600 font-bold text-xs rounded-xl">Reject</button>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}

        {tab === 'docs' && (
          <div className="p-5 space-y-4">
            <div className="flex items-center gap-3">
              <select value={selEmp} onChange={(e) => setSelEmp(e.target.value)} className="input max-w-xs">
                <option value="">Select employee...</option>
                {data.employees.map((e) => (<option key={e.id} value={e.id}>{e.fullName} ({e.employeeCode})</option>))}
              </select>
              {selEmp && (
                <>
                  <button onClick={() => handleGenerate('OfferLetter')} className="px-4 py-2 bg-navy dark:bg-navy-dark text-white font-bold text-xs rounded-xl">Offer letter</button>
                  <button onClick={() => handleGenerate('JoiningLetter')} className="px-4 py-2 bg-navy dark:bg-navy-dark text-white font-bold text-xs rounded-xl">Joining letter</button>
                  <button onClick={() => handleGenerate('Form16')} className="px-4 py-2 bg-navy dark:bg-navy-dark text-white font-bold text-xs rounded-xl">Form 16</button>
                  <button onClick={() => handleGenerate('InternshipCompletionLetter')} className="px-4 py-2 bg-navy dark:bg-navy-dark text-white font-bold text-xs rounded-xl">Internship letter</button>
                  <button onClick={handleAutoGenerate} className="px-4 py-2 bg-gradient-to-r from-gold-1 to-gold-2 text-navy-dark font-bold text-xs rounded-xl">Auto-generate all</button>
                </>
              )}
            </div>
            <div className="space-y-2">
              {docs.map((d) => (
                <div key={d.id} className="p-4 rounded-xl border border-navy/10 dark:border-white/10 bg-white dark:bg-[var(--bg-secondary)] flex items-center justify-between">
                  <div>
                    <span className="font-bold text-navy dark:text-white text-sm">{d.documentName}</span>
                    <span className="text-xs text-navy/50 dark:text-white/50 ml-3">{d.documentType}</span>
                    <span className={`ml-3 text-[10px] px-2 py-0.5 rounded font-bold ${
                      d.status === 'Generated' ? 'bg-amber-50 dark:bg-amber-900/30 text-amber-700' :
                      d.status === 'Sent' ? 'bg-emerald-50 dark:bg-emerald-900/30 text-emerald-700' : 'bg-blue-50 dark:bg-blue-900/30 text-blue-700'
                    }`}>{d.status}</span>
                    <div className="text-xs text-navy/50 dark:text-white/50 mt-1">Generated: {new Date(d.generatedOn).toLocaleDateString()}</div>
                  </div>
                  {d.status === 'Generated' && (
                    <button onClick={async () => { await markDocumentSent(d.id); refreshDocs() }} className="px-3 py-1.5 border border-emerald-200 text-emerald-600 font-bold text-xs rounded-xl">Mark sent</button>
                  )}
                </div>
              ))}
              {!selEmp && <p className="text-xs text-navy/50 dark:text-white/50 text-center py-8">Select an employee to view and manage documents.</p>}
            </div>
          </div>
        )}

        {tab === 'templates' && (
          <div className="p-5 space-y-4">
            <div className="grid md:grid-cols-4 gap-3 p-4 rounded-xl border border-navy/10 dark:border-white/10 bg-amber-50/30">
              <input value={templateForm.name} onChange={(e) => setTemplateForm((s) => ({ ...s, name: e.target.value }))} className="input" placeholder="Template name" />
              <select value={templateForm.documentType} onChange={(e) => setTemplateForm((s) => ({ ...s, documentType: e.target.value }))} className="input">
                <option value="OfferLetter">Offer Letter</option>
                <option value="JoiningLetter">Joining Letter</option>
                <option value="InternshipCompletionLetter">Internship Completion Letter</option>
                <option value="Form16">Form 16</option>
                <option value="Visa">Visa</option>
                <option value="Other">Other</option>
              </select>
              <input value={templateForm.description} onChange={(e) => setTemplateForm((s) => ({ ...s, description: e.target.value }))} className="input" placeholder="Description" />
              <button onClick={handleCreateTemplate} className="px-4 py-2 bg-gradient-to-r from-gold-1 to-gold-2 text-navy-dark font-bold text-xs rounded-xl">Create template</button>
            </div>
            <div>
              <label className="text-xs font-bold text-navy/70 dark:text-white/70 block mb-1">Template HTML (use {'{{FullName}}'}, {'{{Designation}}'}, {'{{CTC}}'}, etc.)</label>
              <textarea value={templateForm.templateContent} onChange={(e) => setTemplateForm((s) => ({ ...s, templateContent: e.target.value }))} className="input w-full h-32 font-mono text-xs" placeholder={`<h1>Offer Letter</h1><p>Dear {{FullName}},</p><p>We are pleased to offer you the position of {{Designation}} at {{CompanyName}}.</p>`} />
            </div>
            <div className="space-y-2">
              {templates.map((t) => (
                <div key={t.id} className="p-3 rounded-xl border border-navy/10 dark:border-white/10 bg-white dark:bg-[var(--bg-secondary)] flex items-center justify-between">
                  <span className="font-bold text-navy dark:text-white text-xs">{t.name} <span className="text-navy/50 dark:text-white/50 font-normal">({t.documentType})</span></span>
                  <span className="text-xs text-navy/50 dark:text-white/50">{t.description}</span>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
