import dotenv from 'dotenv';
dotenv.config();
import express from 'express';
import cors from 'cors';
import morgan from 'morgan';
import helmet from 'helmet';
import connectDB from './config/db.js';
import errorHandler from './middleware/errorHandler.js';

import authRoutes from './routes/authRoutes.js';
import employeeRoutes from './routes/employeeRoutes.js';
import leaveRoutes from './routes/leaveRoutes.js';
import attendanceRoutes from './routes/attendanceRoutes.js';
import payrollRoutes from './routes/payrollRoutes.js';
import recruitmentRoutes from './routes/recruitmentRoutes.js';
import onboardingRoutes from './routes/onboardingRoutes.js';
import shiftRoutes from './routes/shiftRoutes.js';
import holidayRoutes from './routes/holidayRoutes.js';
import performanceRoutes from './routes/performanceRoutes.js';
import trainingRoutes from './routes/trainingRoutes.js';
import assetRoutes from './routes/assetRoutes.js';
import ticketRoutes from './routes/ticketRoutes.js';
import travelExpenseRoutes from './routes/travelExpenseRoutes.js';
import documentRoutes from './routes/documentRoutes.js';
import surveyRoutes from './routes/surveyRoutes.js';
import complianceRoutes from './routes/complianceRoutes.js';
import workflowRoutes from './routes/workflowRoutes.js';
import notificationRoutes from './routes/notificationRoutes.js';
import separationRoutes from './routes/separationRoutes.js';
import roleRoutes from './routes/roleRoutes.js';
import settingsRoutes from './routes/settingsRoutes.js';
import analyticsRoutes from './routes/analyticsRoutes.js';
import reportRoutes from './routes/reportRoutes.js';
import dashboardRoutes from './routes/dashboardRoutes.js';
import aiRoutes from './routes/aiRoutes.js';
import socialRoutes from './routes/socialRoutes.js';
import alumniRoutes from './routes/alumniRoutes.js';
import expenseRoutes from './routes/expenseRoutes.js';
import resilienceRoutes from './routes/resilienceRoutes.js';
import fnfRoutes from './routes/fnfRoutes.js';
import integrationRoutes from './routes/integrationRoutes.js';
import aiCouncilRoutes from './routes/aiCouncilRoutes.js';
import visaRoutes from './routes/visaRoutes.js';
import leaveTypeRoutes from './routes/leaveTypeRoutes.js';
import certificationRoutes from './routes/certificationRoutes.js';
import sddPipelineRoutes from './routes/sddPipelineRoutes.js';
import aiIntegrationRouter from './routes/aiIntegrationRouter.js';
import workforceRoutes from './routes/workforceRoutes.js';
import internalMobilityRoutes from './routes/internalMobilityRoutes.js';
import benefitsRoutes from './routes/benefitsRoutes.js';
import contractorRoutes from './routes/contractorRoutes.js';
import visitorRoutes from './routes/visitorRoutes.js';
import caseRoutes from './routes/caseRoutes.js';
import smartFormRoutes from './routes/smartFormRoutes.js';
import talentAnalyticsRoutes from './routes/talentAnalyticsRoutes.js';
import documentTemplateRoutes from './routes/documentTemplateRoutes.js';
import serviceCategoryRoutes from './routes/serviceCategoryRoutes.js';
import serviceCatalogRoutes from './routes/serviceCatalogRoutes.js';
import serviceRequestRoutes from './routes/serviceRequestRoutes.js';
import itAssetRoutes from './routes/itAssetRoutes.js';
import softwareLicenseRoutes from './routes/softwareLicenseRoutes.js';
import licenseAllocationRoutes from './routes/licenseAllocationRoutes.js';
import purchaseRequisitionRoutes from './routes/purchaseRequisitionRoutes.js';
import purchaseOrderRoutes from './routes/purchaseOrderRoutes.js';
import goodsReceiptRoutes from './routes/goodsReceiptRoutes.js';
import invoiceRoutes from './routes/invoiceRoutes.js';
import policyRoutes from './routes/policyRoutes.js';
import policyAcknowledgmentRoutes from './routes/policyAcknowledgmentRoutes.js';
import profileChangeRequestRoutes from './routes/profileChangeRequestRoutes.js';
import gatePassRoutes from './routes/gatePassRoutes.js';
import virtualIdCardRoutes from './routes/virtualIdCardRoutes.js';
import workspaceRoutes from './routes/workspaceRoutes.js';
import excelRoutes from './routes/excelRoutes.js';
import newsRoutes from './routes/newsRoutes.js';

const app = express();

connectDB();

app.use(helmet());
app.use(cors());
app.use(morgan('dev'));
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: false }));


app.get('/api/health', (req, res) => {
  res.status(200).json({ success: true, message: 'ReliSoft HR API is healthy' });
});

app.use('/api/auth', authRoutes);
app.use('/api/employees', employeeRoutes);
app.use('/api/leaves', leaveRoutes);
app.use('/api/attendance', attendanceRoutes);
app.use('/api/payroll', payrollRoutes);
app.use('/api/recruitment', recruitmentRoutes);
app.use('/api/onboarding', onboardingRoutes);
app.use('/api/shifts', shiftRoutes);
app.use('/api/holidays', holidayRoutes);
app.use('/api/performance', performanceRoutes);
app.use('/api/training', trainingRoutes);
app.use('/api/assets', assetRoutes);
app.use('/api/tickets', ticketRoutes);
app.use('/api/travel-expenses', travelExpenseRoutes);
app.use('/api/documents', documentRoutes);
app.use('/api/surveys', surveyRoutes);
app.use('/api/compliance', complianceRoutes);
app.use('/api/workflows', workflowRoutes);
app.use('/api/notifications', notificationRoutes);
app.use('/api/separation', separationRoutes);
app.use('/api/roles', roleRoutes);
app.use('/api/settings', settingsRoutes);
app.use('/api/analytics', analyticsRoutes);
app.use('/api/reports', reportRoutes);
app.use('/api/dashboard', dashboardRoutes);
app.use('/api/ai', aiRoutes);
app.use('/api/social', socialRoutes);
app.use('/api/alumni', alumniRoutes);
app.use('/api/expenses', expenseRoutes);

app.use('/api/resilience', resilienceRoutes);
app.use('/api/fnf', fnfRoutes);
app.use('/api/integrations', integrationRoutes);
app.use('/api/ai-council', aiCouncilRoutes);
app.use('/api/visa', visaRoutes);
app.use('/api/leave-types', leaveTypeRoutes);
app.use('/api/certifications', certificationRoutes);

app.use('/api/sdd', sddPipelineRoutes);
app.use('/api/ai-integration', aiIntegrationRouter());
app.use('/api/workforce', workforceRoutes);
app.use('/api/internal-mobility', internalMobilityRoutes);
app.use('/api/benefits', benefitsRoutes);
app.use('/api/contractors', contractorRoutes);
app.use('/api/visitors', visitorRoutes);
app.use('/api/cases', caseRoutes);
app.use('/api/forms', smartFormRoutes);
app.use('/api/talent-analytics', talentAnalyticsRoutes);
app.use('/api/document-templates', documentTemplateRoutes);

app.use('/api/service-categories', serviceCategoryRoutes);
app.use('/api/service-catalog', serviceCatalogRoutes);
app.use('/api/service-requests', serviceRequestRoutes);
app.use('/api/it-assets', itAssetRoutes);
app.use('/api/software-licenses', softwareLicenseRoutes);
app.use('/api/license-allocations', licenseAllocationRoutes);
app.use('/api/purchase-requisitions', purchaseRequisitionRoutes);
app.use('/api/purchase-orders', purchaseOrderRoutes);
app.use('/api/goods-receipts', goodsReceiptRoutes);
app.use('/api/invoices', invoiceRoutes);
app.use('/api/policies', policyRoutes);
app.use('/api/policy-acknowledgments', policyAcknowledgmentRoutes);
app.use('/api/profile-change-requests', profileChangeRequestRoutes);
app.use('/api/gate-passes', gatePassRoutes);
app.use('/api/virtual-id-cards', virtualIdCardRoutes);
app.use('/api/workspace', workspaceRoutes);
app.use('/api/excel', excelRoutes);
app.use('/api/news', newsRoutes);

app.use(errorHandler);

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
  console.log(`ReliSoft HR API running on port ${PORT}`);
});

export default app;
