using Microsoft.EntityFrameworkCore;
using RelisoftHR.Data;
using RelisoftHR.Models;

namespace RelisoftHR.Services;

/// <summary>
/// Seeds a rich demo dataset on top of the base seeders so that every
/// screen and endpoint has data to show — no empty-state 404s.
/// Idempotent: each section only runs when its target table is missing
/// the demo records it manages.
/// </summary>
public static class DemoSeedService
{
    private static bool IsSqlite(AppDbContext db) =>
        db.Database.ProviderName?.Contains("Sqlite", StringComparison.OrdinalIgnoreCase) == true;

    public sealed record SeedReport(
        int Onboardings, int Documents, int Probations, int PayRuns, int Payslips,
        int Surveys, int Reviews, int Awards, int Assets, int Shifts,
        int Announcements, int Articles, int Holidays, int Attendance,
        int Timesheets, int Discussions, int Encashments, int Regularizations,
        int Offboardings, int Visitors, int MedicalCerts);

    public static async Task<SeedReport> SeedAsync(AppDbContext db)
    {
        var utc = DateTime.UtcNow;
        var today = DateOnly.FromDateTime(DateTime.Today);
        var docsDir = Path.Combine(Directory.GetCurrentDirectory(), "App_Data", "Documents");
        var medicalDir = Path.Combine(Directory.GetCurrentDirectory(), "App_Data", "MedicalCertificates");
        Directory.CreateDirectory(docsDir);
        Directory.CreateDirectory(medicalDir);

        var report = new SeedReport(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

        report = await SeedMedicalCertificatesAsync(db, report, medicalDir);
        report = await SeedOnboardingAsync(db, report, docsDir);
        report = await SeedProbationsAsync(db, report);
        report = await SeedPayrollAsync(db, report);
        report = await SeedSurveysAsync(db, report);
        report = await SeedReviewsAsync(db, report);
        report = await SeedRecognitionAsync(db, report);
        report = await SeedAssetsAsync(db, report);
        report = await SeedShiftsAsync(db, report);
        report = await SeedAnnouncementsAsync(db, report, utc);
        report = await SeedKnowledgeBaseAsync(db, report, utc);
        report = await SeedHolidaysAsync(db, report, today);
        report = await SeedAttendanceAsync(db, report, utc, today);
        report = await SeedTimesheetsAsync(db, report, utc, today);
        report = await SeedSalaryDiscussionsAsync(db, report, utc);
        report = await SeedEncashmentsAsync(db, report, utc);
        report = await SeedRegularizationsAsync(db, report, utc, today);
        report = await SeedOffboardingAsync(db, report, utc);
        report = await SeedVisitorsAsync(db, report, utc, today);

        return report;
    }

    // ------------------------------------------------------------------
    // Leave medical certificate — makes /api/leave/{id}/download-medical work.
    // ------------------------------------------------------------------
    private static async Task<SeedReport> SeedMedicalCertificatesAsync(AppDbContext db, SeedReport r, string medicalDir)
    {
        var leave = await db.LeaveApplications.FirstOrDefaultAsync(l => l.IsMedicalLeave && !string.IsNullOrEmpty(l.MedicalCertificatePath));
        if (leave != null) return r;

        var candidate = await db.LeaveApplications
            .FirstOrDefaultAsync(l => string.IsNullOrEmpty(l.MedicalCertificatePath));
        if (candidate == null) return r;

        var dir = Path.Combine(medicalDir, candidate.EmployeeId.ToString());
        Directory.CreateDirectory(dir);
        var path = Path.Combine(dir, "demo-medical-certificate.txt");
        await File.WriteAllTextAsync(path,
            "ReliSoft HR Portal - Demo medical certificate.\n" +
            "This placeholder file is generated by the demo seed so the download-medical endpoint has a real file to serve.\n" +
            $"Generated: {DateTime.UtcNow:O}\n");

        candidate.MedicalCertificatePath = path;
        candidate.IsMedicalLeave = true;
        await db.SaveChangesAsync();
        return r with { MedicalCerts = r.MedicalCerts + 1 };
    }

    // ------------------------------------------------------------------
    // Onboarding checklist + completed onboarding for existing employees.
    // ------------------------------------------------------------------
    private static async Task<SeedReport> SeedOnboardingAsync(AppDbContext db, SeedReport r, string docsDir)
    {
        if (!await db.OnboardingChecklistItems.AnyAsync())
        {
            db.OnboardingChecklistItems.AddRange(
                new OnboardingChecklistItem { Name = "Offer Letter Accepted", Description = "Signed offer letter received", IsMandatory = true, SortOrder = 1 },
                new OnboardingChecklistItem { Name = "ID Card Issued", Description = "Company ID card created", IsMandatory = true, SortOrder = 2 },
                new OnboardingChecklistItem { Name = "Bank Details Collected", Description = "Salary bank account verified", IsMandatory = true, SortOrder = 3 },
                new OnboardingChecklistItem { Name = "Laptop Assigned", Description = "Work laptop handed over", IsMandatory = true, SortOrder = 4 },
                new OnboardingChecklistItem { Name = "Email & Access Setup", Description = "Company email and systems access", IsMandatory = true, SortOrder = 5 },
                new OnboardingChecklistItem { Name = "Induction Completed", Description = "Intro to team and policies", IsMandatory = true, SortOrder = 6 }
            );
            await db.SaveChangesAsync();
        }

        var items = await db.OnboardingChecklistItems.OrderBy(i => i.SortOrder).ToListAsync();
        var employeeIds = await db.Employees.Select(e => e.Id).ToListAsync();

        foreach (var employeeId in employeeIds)
        {
            if (await db.EmployeeOnboardings.AnyAsync(o => o.EmployeeId == employeeId)) continue;

            var onboarding = new EmployeeOnboarding
            {
                EmployeeId = employeeId,
                Status = "Completed",
                TotalSteps = items.Count,
                CompletedSteps = items.Count,
                CompletedOn = utcNow(),
                CreatedOn = utcNow()
            };
            db.EmployeeOnboardings.Add(onboarding);
            await db.SaveChangesAsync();

            db.EmployeeOnboardingSteps.AddRange(items.Select(ci => new EmployeeOnboardingStep
            {
                OnboardingId = onboarding.Id,
                ChecklistItemId = ci.Id,
                Status = "Completed",
                CompletedOn = utcNow()
            }));
            await db.SaveChangesAsync();
            r = r with { Onboardings = r.Onboardings + 1 };

            if (!await db.EmployeeOnboardingProfiles.AnyAsync(p => p.EmployeeId == employeeId))
            {
                var profile = new EmployeeOnboardingProfile { EmployeeId = employeeId, HasPriorExperience = true, CreatedOn = utcNow() };
                db.EmployeeOnboardingProfiles.Add(profile);
                await db.SaveChangesAsync();
            }
        }

        // Guarantee an onboarding document with Id = 1 so /api/onboarding/documents/1 is deterministic.
        var doc = await db.EmployeeOnboardingDocuments.AsNoTracking().FirstOrDefaultAsync(d => d.Id == 1);
        if (doc == null)
        {
            var profile = await db.EmployeeOnboardingProfiles.OrderBy(p => p.Id).FirstOrDefaultAsync();
            if (profile != null)
            {
                var docPath = Path.Combine(docsDir, "demo-offer-letter.txt");
                await File.WriteAllTextAsync(docPath,
                    "ReliSoft HR Portal - Demo offer letter placeholder.\nGenerated by the demo seed for the onboarding documents endpoint.\n");
                if (IsSqlite(db))
                {
                    await db.Database.ExecuteSqlInterpolatedAsync($@"
                        INSERT INTO EmployeeOnboardingDocuments
                            (Id, OnboardingProfileId, DocumentType, OriginalFileName, StoredFilePath, UploadedOn)
                        VALUES (1, {profile.Id}, 'OfferLetter', 'offer-letter-demo.txt', {docPath}, {utcNow()});");
                }
                else
                {
                    await db.Database.ExecuteSqlInterpolatedAsync($@"
                        SET IDENTITY_INSERT EmployeeOnboardingDocuments ON;
                        INSERT INTO EmployeeOnboardingDocuments
                            (Id, OnboardingProfileId, DocumentType, OriginalFileName, StoredFilePath, UploadedOn)
                        VALUES (1, {profile.Id}, 'OfferLetter', 'offer-letter-demo.txt', {docPath}, {utcNow()});
                        SET IDENTITY_INSERT EmployeeOnboardingDocuments OFF;");
                }
                r = r with { Documents = r.Documents + 1 };
            }
        }

        // One candidate still in progress so the onboarding dashboard shows action.
        if (!await db.EmployeeOnboardings.AnyAsync(o => o.Status == "InProgress"))
        {
            var empId = await db.Employees.Select(e => e.Id).FirstOrDefaultAsync();
            if (empId != 0)
            {
                var onboarding = await db.EmployeeOnboardings.FirstOrDefaultAsync(o => o.EmployeeId == empId);
                if (onboarding != null && onboarding.Status == "Completed")
                {
                    onboarding.Status = "InProgress";
                    onboarding.CompletedSteps = Math.Max(0, onboarding.TotalSteps - 2);
                    await db.SaveChangesAsync();
                }
            }
        }

        return r;
    }

    private static DateTime utcNow() => DateTime.UtcNow;

    // ------------------------------------------------------------------
    // Probation records — /api/hr-v2/probation/{employeeId}.
    // ------------------------------------------------------------------
    private static async Task<SeedReport> SeedProbationsAsync(AppDbContext db, SeedReport r)
    {
        var toSeed = new[]
        {
            (EmployeeId: 1, Status: "Confirmed", Extensions: 0),
            (EmployeeId: 3, Status: "Confirmed", Extensions: 0),
            (EmployeeId: 7, Status: "Probation", Extensions: 1),
            (EmployeeId: 9, Status: "Probation", Extensions: 0),
            (EmployeeId: 10, Status: "Probation", Extensions: 0)
        };

        foreach (var (employeeId, status, extensions) in toSeed)
        {
            if (!await db.Employees.AnyAsync(e => e.Id == employeeId)) continue;
            if (await db.EmployeeProbations.AnyAsync(p => p.EmployeeId == employeeId)) continue;

            var start = new DateTime(2025, 9, 1, 0, 0, 0, DateTimeKind.Utc);
            db.EmployeeProbations.Add(new EmployeeProbation
            {
                EmployeeId = employeeId,
                StartDate = start,
                OriginalEndDate = start.AddMonths(6),
                CurrentEndDate = status == "Confirmed" ? start.AddMonths(6) : start.AddMonths(6).AddMonths(extensions),
                ExtensionCount = extensions,
                Status = status,
                Notes = status == "Confirmed" ? "Confirmed on successful completion of probation." : "Probation in progress.",
                ConfirmedOn = status == "Confirmed" ? start.AddMonths(6) : null,
                CreatedOn = utcNow()
            });
            await db.SaveChangesAsync();
            r = r with { Probations = r.Probations + 1 };
        }
        return r;
    }

    // ------------------------------------------------------------------
    // Payroll: salary structures, one processed pay run with payslips.
    // ------------------------------------------------------------------
    private static async Task<SeedReport> SeedPayrollAsync(AppDbContext db, SeedReport r)
    {
        var components = await db.PayComponents.ToListAsync();
        if (components.Count == 0) return r;
        var basic = components.FirstOrDefault(c => c.Name == "Basic Salary");
        var hra = components.FirstOrDefault(c => c.Name == "House Rent Allowance");
        var pf = components.FirstOrDefault(c => c.Name == "Provident Fund (PF)");

        var payees = new[] { 1, 2, 3, 7, 9, 10, 11, 12 };

        // Salary structures for a few employees
        foreach (var employeeId in payees)
        {
            if (!await db.Employees.AnyAsync(e => e.Id == employeeId)) continue;
            if (await db.EmployeeSalaryStructures.AnyAsync(s => s.EmployeeId == employeeId)) continue;

            var structure = new EmployeeSalaryStructure
            {
                EmployeeId = employeeId,
                EffectiveFrom = new DateTime(2026, 4, 1, 0, 0, 0, DateTimeKind.Utc),
                CreatedOn = utcNow()
            };
            db.EmployeeSalaryStructures.Add(structure);
            await db.SaveChangesAsync();

            var monthly = 60000m + (employeeId * 5000m);
            db.EmployeeSalaryStructureLines.AddRange(
                new EmployeeSalaryStructureLine { SalaryStructureId = structure.Id, PayComponentId = basic!.Id, MonthlyAmount = monthly * 0.5m },
                new EmployeeSalaryStructureLine { SalaryStructureId = structure.Id, PayComponentId = hra!.Id, MonthlyAmount = monthly * 0.3m },
                new EmployeeSalaryStructureLine { SalaryStructureId = structure.Id, PayComponentId = pf!.Id, MonthlyAmount = monthly * 0.12m }
            );
            await db.SaveChangesAsync();
        }

        // Guarantee a Processed/Paid pay run with Id = 1 so /api/payroll/runs/1 and
        // /api/payroll/runs/1/export are deterministic (existing runs may start at a higher id).
        var seededRun = await db.PayRuns.AsNoTracking().FirstOrDefaultAsync(r => r.Id == 1);
        if (seededRun == null)
        {
            // Use the previous month so the seeded run never collides with the current month's run.
            var now = DateTime.UtcNow.AddMonths(-1);
            if (IsSqlite(db))
            {
                await db.Database.ExecuteSqlInterpolatedAsync($@"
                    INSERT INTO PayRuns (Id, PeriodMonth, PeriodYear, Status, ProcessedOn, PaidOn, AutoDisbursed, CreatedOn)
                    VALUES (1, {now.Month}, {now.Year}, {(int)PayRunStatus.Paid}, {now}, {now}, 0, {now});");
            }
            else
            {
                await db.Database.ExecuteSqlInterpolatedAsync($@"
                    SET IDENTITY_INSERT PayRuns ON;
                    INSERT INTO PayRuns (Id, PeriodMonth, PeriodYear, Status, ProcessedOn, PaidOn, AutoDisbursed, CreatedOn)
                    VALUES (1, {now.Month}, {now.Year}, {(int)PayRunStatus.Paid}, {now}, {now}, 0, {now});
                    SET IDENTITY_INSERT PayRuns OFF;");
            }
            r = r with { PayRuns = r.PayRuns + 1 };
        }
        else if (seededRun.Status != PayRunStatus.Paid)
        {
            // Existing demo DBs carry run 1 as "Ready" (the old Processed value). Mark it
            // Paid so the demo shows a completed salary-shot run.
            await db.Database.ExecuteSqlInterpolatedAsync($@"
                UPDATE PayRuns SET Status = {(int)PayRunStatus.Paid},
                    ProcessedOn = COALESCE(ProcessedOn, {DateTime.UtcNow}),
                    PaidOn = COALESCE(PaidOn, {DateTime.UtcNow})
                WHERE Id = 1;");
        }

        // Payslips for the seeded run.
        if (!await db.Payslips.AnyAsync(p => p.PayRunId == 1))
        {
            foreach (var employeeId in payees)
            {
                if (!await db.Employees.AnyAsync(e => e.Id == employeeId)) continue;
                var monthly = 60000m + (employeeId * 5000m);
                var gross = monthly * 0.8m;
                var deductions = monthly * 0.12m;
                var net = gross - deductions;

                var payslip = new Payslip
                {
                    PayRunId = 1,
                    EmployeeId = employeeId,
                    GrossEarnings = gross,
                    TotalDeductions = deductions,
                    NetPay = net
                };
                db.Payslips.Add(payslip);
                await db.SaveChangesAsync();

                db.PayslipLines.AddRange(
                    new PayslipLine { PayslipId = payslip.Id, PayComponentId = basic!.Id, ComponentName = basic.Name, Type = PayComponentType.Earning, Amount = gross },
                    new PayslipLine { PayslipId = payslip.Id, PayComponentId = pf!.Id, ComponentName = pf.Name, Type = PayComponentType.Deduction, Amount = deductions }
                );
                await db.SaveChangesAsync();
                r = r with { Payslips = r.Payslips + 1 };
            }
        }
        return r;
    }

    // ------------------------------------------------------------------
    // Surveys — /api/surveys/{id} and /api/surveys/{id}/results.
    // ------------------------------------------------------------------
    private static async Task<SeedReport> SeedSurveysAsync(AppDbContext db, SeedReport r)
    {
        var creator = await db.Employees.OrderBy(e => e.Id).FirstOrDefaultAsync();
        if (creator == null) return r;

        var survey = await db.Surveys.AsNoTracking().FirstOrDefaultAsync(s => s.Id == 1);
        if (survey == null)
        {
            var now = DateTime.UtcNow;
            if (IsSqlite(db))
            {
                await db.Database.ExecuteSqlInterpolatedAsync($@"
                    INSERT INTO Surveys (Id, Title, Description, StartDate, EndDate, IsAnonymous, IsActive, CreatedById, CreatedOn)
                    VALUES (1, 'Employee Engagement Pulse', 'Quarterly pulse survey to understand engagement across teams.',
                            {now.AddDays(-10)}, {now.AddDays(20)}, 1, 1, {creator.Id}, {now});");
            }
            else
            {
                await db.Database.ExecuteSqlInterpolatedAsync($@"
                    SET IDENTITY_INSERT Surveys ON;
                    INSERT INTO Surveys (Id, Title, Description, StartDate, EndDate, IsAnonymous, IsActive, CreatedById, CreatedOn)
                    VALUES (1, 'Employee Engagement Pulse', 'Quarterly pulse survey to understand engagement across teams.',
                            {now.AddDays(-10)}, {now.AddDays(20)}, 1, 1, {creator.Id}, {now});
                    SET IDENTITY_INSERT Surveys OFF;");
            }
            r = r with { Surveys = r.Surveys + 1 };
        }

        if (!await db.SurveyQuestions.AnyAsync(q => q.SurveyId == 1))
        {
            db.SurveyQuestions.AddRange(
                new SurveyQuestion { SurveyId = 1, QuestionText = "How satisfied are you with your role?", QuestionType = "rating", Options = "1,2,3,4,5", SortOrder = 1, IsRequired = true },
                new SurveyQuestion { SurveyId = 1, QuestionText = "Do you feel valued at work?", QuestionType = "choice", Options = "Yes,No,Sometimes", SortOrder = 2, IsRequired = true },
                new SurveyQuestion { SurveyId = 1, QuestionText = "Any suggestions for us?", QuestionType = "text", SortOrder = 3, IsRequired = false }
            );
            await db.SaveChangesAsync();
        }

        var q1 = await db.SurveyQuestions.FirstAsync(q => q.SurveyId == 1 && q.SortOrder == 1);
        var q2 = await db.SurveyQuestions.FirstAsync(q => q.SurveyId == 1 && q.SortOrder == 2);
        var q3 = await db.SurveyQuestions.FirstAsync(q => q.SurveyId == 1 && q.SortOrder == 3);

        if (!await db.SurveyResponses.AnyAsync(sr => sr.SurveyId == 1))
        {
            var respondents = await db.Employees.Select(e => e.Id).ToListAsync();
            foreach (var employeeId in respondents)
            {
                db.SurveyResponses.AddRange(
                    new SurveyResponse { SurveyId = 1, QuestionId = q1.Id, EmployeeId = employeeId, Response = ((employeeId % 5) + 1).ToString(), CreatedOn = utcNow() },
                    new SurveyResponse { SurveyId = 1, QuestionId = q2.Id, EmployeeId = employeeId, Response = employeeId % 2 == 0 ? "Yes" : "Sometimes", CreatedOn = utcNow() },
                    new SurveyResponse { SurveyId = 1, QuestionId = q3.Id, EmployeeId = employeeId, Response = "Keep shipping product improvements.", CreatedOn = utcNow() }
                );
            }
            await db.SaveChangesAsync();
        }
        return r;
    }

    // ------------------------------------------------------------------
    // Performance reviews — /api/reviews/{id} and /api/reviews/employee/{id}.
    // ------------------------------------------------------------------
    private static async Task<SeedReport> SeedReviewsAsync(AppDbContext db, SeedReport r)
    {
        var reviewer = await db.Employees.OrderBy(e => e.Id).FirstOrDefaultAsync();
        if (reviewer == null) return r;

        var review = await db.PerformanceReviews.AsNoTracking().FirstOrDefaultAsync(x => x.Id == 1);
        if (review == null)
        {
            var now = DateTime.UtcNow;
            if (IsSqlite(db))
            {
                await db.Database.ExecuteSqlInterpolatedAsync($@"
                    INSERT INTO PerformanceReviews
                        (Id, EmployeeId, ReviewerId, ReviewType, ReviewDate, Status, KeyStrengths, AreasOfImprovement,
                         TrainingSupportRequired, Recommendation, EligibleForRoleEnhancement, OverallRating, OverallAssessment, CompletedOn, CreatedOn)
                    VALUES (1, 3, {reviewer.Id}, {(int)ReviewType.Yearly}, {now.AddDays(-15)}, {(int)PerformanceReviewStatus.Completed},
                            'Strong ownership, timely delivery and good communication.', 'Can improve on documentation depth.',
                            'Advanced cloud computing workshop.', 'Retain and develop.', 1, 4.5, 'Exceeds expectations', {now.AddDays(-15)}, {now});");
            }
            else
            {
                await db.Database.ExecuteSqlInterpolatedAsync($@"
                    SET IDENTITY_INSERT PerformanceReviews ON;
                    INSERT INTO PerformanceReviews
                        (Id, EmployeeId, ReviewerId, ReviewType, ReviewDate, Status, KeyStrengths, AreasOfImprovement,
                         TrainingSupportRequired, Recommendation, EligibleForRoleEnhancement, OverallRating, OverallAssessment, CompletedOn, CreatedOn)
                    VALUES (1, 3, {reviewer.Id}, {(int)ReviewType.Yearly}, {now.AddDays(-15)}, {(int)PerformanceReviewStatus.Completed},
                            'Strong ownership, timely delivery and good communication.', 'Can improve on documentation depth.',
                            'Advanced cloud computing workshop.', 'Retain and develop.', 1, 4.5, 'Exceeds expectations', {now.AddDays(-15)}, {now});
                    SET IDENTITY_INSERT PerformanceReviews OFF;");
            }
            r = r with { Reviews = r.Reviews + 1 };
        }

        if (!await db.ReviewCriterionScores.AnyAsync(c => c.PerformanceReviewId == 1))
        {
            db.ReviewCriterionScores.AddRange(ReviewCriteriaCatalog.All.Select(c => new ReviewCriterionScore
            {
                PerformanceReviewId = 1,
                Category = c.Category,
                Title = c.Title,
                WeightPercent = c.WeightPercent,
                Rating = 4,
                Remarks = "On track"
            }));
            await db.SaveChangesAsync();
        }

        // Ensure the reviewed employee also has reviews they can view.
        var reviewees = new[] { 7, 10 };
        foreach (var employeeId in reviewees)
        {
            if (!await db.Employees.AnyAsync(e => e.Id == employeeId)) continue;
            if (await db.PerformanceReviews.AnyAsync(x => x.EmployeeId == employeeId)) continue;

            var own = new PerformanceReview
            {
                EmployeeId = employeeId,
                ReviewerId = reviewer.Id,
                ReviewType = ReviewType.Yearly,
                ReviewDate = DateTime.UtcNow.AddDays(-15),
                Status = PerformanceReviewStatus.Completed,
                KeyStrengths = "Strong ownership and timely delivery.",
                AreasOfImprovement = "Can improve on documentation depth.",
                Recommendation = "Retain and develop.",
                OverallRating = 4.0m + (employeeId % 2) * 0.5m,
                OverallAssessment = "Meets expectations",
                CompletedOn = DateTime.UtcNow.AddDays(-15),
                CreatedOn = utcNow()
            };
            db.PerformanceReviews.Add(own);
            await db.SaveChangesAsync();

            db.ReviewCriterionScores.AddRange(ReviewCriteriaCatalog.All.Select(c => new ReviewCriterionScore
            {
                PerformanceReviewId = own.Id,
                Category = c.Category,
                Title = c.Title,
                WeightPercent = c.WeightPercent,
                Rating = 3 + (employeeId % 2),
                Remarks = "On track"
            }));
            await db.SaveChangesAsync();
            r = r with { Reviews = r.Reviews + 1 };
        }
        return r;
    }

    // ------------------------------------------------------------------
    // Recognition — /api/recognition/awards/{id}.
    // ------------------------------------------------------------------
    private static async Task<SeedReport> SeedRecognitionAsync(AppDbContext db, SeedReport r)
    {
        var creator = await db.Employees.OrderBy(e => e.Id).FirstOrDefaultAsync();
        if (creator == null) return r;

        var award = await db.RecognitionAwards.AsNoTracking().FirstOrDefaultAsync(a => a.Id == 1);
        if (award == null)
        {
            var now = DateTime.UtcNow;
            if (IsSqlite(db))
            {
                await db.Database.ExecuteSqlInterpolatedAsync($@"
                    INSERT INTO RecognitionAwards
                        (Id, Title, Description, Category, Scope, PeriodLabel, ImageUrl, AwardPoints, CreatedOn, CreatedByEmployeeId)
                    VALUES (1, 'Star of the Month', 'Recognised for outstanding contribution to the HR Portal delivery.',
                            'Individual', 'Monthly', {now.ToString("MMM yyyy")}, '', 100, {now}, {creator.Id});");
            }
            else
            {
                await db.Database.ExecuteSqlInterpolatedAsync($@"
                    SET IDENTITY_INSERT RecognitionAwards ON;
                    INSERT INTO RecognitionAwards
                        (Id, Title, Description, Category, Scope, PeriodLabel, ImageUrl, AwardPoints, CreatedOn, CreatedByEmployeeId)
                    VALUES (1, 'Star of the Month', 'Recognised for outstanding contribution to the HR Portal delivery.',
                            'Individual', 'Monthly', {now.ToString("MMM yyyy")}, '', 100, {now}, {creator.Id});
                    SET IDENTITY_INSERT RecognitionAwards OFF;");
            }
            r = r with { Awards = r.Awards + 1 };
        }

        if (!await db.RecognitionAwardRecipients.AnyAsync(rec => rec.AwardId == 1))
        {
            var recipients = await db.Employees.Where(e => e.Id == 3 || e.Id == 7).ToListAsync();
            foreach (var emp in recipients)
            {
                db.RecognitionAwardRecipients.Add(new RecognitionAwardRecipient
                {
                    AwardId = 1,
                    EmployeeId = emp.Id,
                    RecognitionType = "Individual",
                    Reason = "Consistent high-quality delivery and team support.",
                    AwardedOn = utcNow(),
                    AwardedByEmployeeId = creator.Id
                });
            }
            await db.SaveChangesAsync();
        }

        if (!await db.Kudos.AnyAsync())
        {
            var giver = await db.Employees.OrderBy(e => e.Id).FirstOrDefaultAsync();
            var giverId = giver?.Id;
            var receiver = await db.Employees.Where(e => e.Id != (giverId ?? 0)).OrderBy(e => e.Id).FirstOrDefaultAsync();
            if (giver != null && receiver != null)
            {
                db.Kudos.Add(new Kudos
                {
                    GiverEmployeeId = giver.Id,
                    ReceiverEmployeeId = receiver.Id,
                    Category = "Teamwork",
                    Message = "Great collaboration on the release!",
                    Points = 10,
                    CreatedOn = utcNow()
                });
                await db.SaveChangesAsync();
            }
        }

        return r;
    }

    // ------------------------------------------------------------------
    // Assets — /api/assets and employee asset list.
    // ------------------------------------------------------------------
    private static async Task<SeedReport> SeedAssetsAsync(AppDbContext db, SeedReport r)
    {
        if (await db.Assets.AnyAsync()) return r;

        var assets = new[]
        {
            new Asset { Name = "Dell Latitude 5540", AssetTag = "LAP-001", Category = "Laptop", SerialNumber = "SN-LAP-001", Status = "Assigned" },
            new Asset { Name = "Lenovo ThinkPad E16", AssetTag = "LAP-002", Category = "Laptop", SerialNumber = "SN-LAP-002", Status = "Available" },
            new Asset { Name = "Dell 24\" Monitor", AssetTag = "MON-001", Category = "Monitor", SerialNumber = "SN-MON-001", Status = "Available" },
            new Asset { Name = "HP LaserJet Printer", AssetTag = "PRN-001", Category = "Printer", SerialNumber = "SN-PRN-001", Status = "Available" },
            new Asset { Name = "iPhone 15 (Work)", AssetTag = "PHN-001", Category = "Phone", SerialNumber = "SN-PHN-001", Status = "Assigned" }
        };
        db.Assets.AddRange(assets);
        await db.SaveChangesAsync();

        if (!await db.EmployeeAssets.AnyAsync())
        {
            var emp3 = await db.Employees.FindAsync(3);
            var emp1 = await db.Employees.FindAsync(1);
            var laptop = assets[0];
            var phone = assets[4];
            if (emp3 != null)
            {
                db.EmployeeAssets.Add(new EmployeeAsset { EmployeeId = 3, AssetId = laptop.Id, AssignedOn = utcNow(), Status = "Assigned" });
                await db.SaveChangesAsync();
            }
            if (emp1 != null)
            {
                db.EmployeeAssets.Add(new EmployeeAsset { EmployeeId = 1, AssetId = phone.Id, AssignedOn = utcNow(), Status = "Assigned" });
                await db.SaveChangesAsync();
            }
        }

        return r with { Assets = r.Assets + assets.Length };
    }

    // ------------------------------------------------------------------
    // Shifts — /api/shifts templates & assignments.
    // ------------------------------------------------------------------
    private static async Task<SeedReport> SeedShiftsAsync(AppDbContext db, SeedReport r)
    {
        if (await db.ShiftTemplates.AnyAsync()) return r;

        var shifts = new[]
        {
            new ShiftTemplate { Name = "Morning Shift", StartTime = new TimeSpan(9, 0, 0), EndTime = new TimeSpan(18, 0, 0), TotalHours = 9, IsNightShift = false, Description = "Standard 9-6 workday" },
            new ShiftTemplate { Name = "Night Shift", StartTime = new TimeSpan(21, 0, 0), EndTime = new TimeSpan(6, 0, 0), TotalHours = 9, IsNightShift = true, Description = "Overnight support shift" },
            new ShiftTemplate { Name = "Hybrid Shift", StartTime = new TimeSpan(10, 0, 0), EndTime = new TimeSpan(19, 0, 0), TotalHours = 9, IsNightShift = false, Description = "Late start workday" }
        };
        db.ShiftTemplates.AddRange(shifts);
        await db.SaveChangesAsync();

        if (!await db.ShiftAssignments.AnyAsync())
        {
            var emp3 = await db.Employees.FindAsync(3);
            if (emp3 != null)
            {
                db.ShiftAssignments.Add(new ShiftAssignment
                {
                    EmployeeId = 3,
                    ShiftTemplateId = shifts[0].Id,
                    StartDate = DateTime.UtcNow.AddDays(-30),
                    IsRecurring = true,
                    DayOfWeek = "Mon-Fri",
                    CreatedOn = utcNow()
                });
                await db.SaveChangesAsync();
            }
        }

        return r with { Shifts = r.Shifts + shifts.Length };
    }

    // ------------------------------------------------------------------
    // Announcements.
    // ------------------------------------------------------------------
    private static async Task<SeedReport> SeedAnnouncementsAsync(AppDbContext db, SeedReport r, DateTime utc)
    {
        if (await db.Announcements.AnyAsync()) return r;

        var author = await db.Employees.OrderBy(e => e.Id).FirstOrDefaultAsync();
        if (author == null) return r;

        db.Announcements.AddRange(
            new Announcement { Title = "Welcome to ReliSoft HR Portal", Content = "The new HR portal is live! Explore leaves, attendance, payroll and more.", Category = "General", Priority = "High", IsActive = true, CreatedById = author.Id, CreatedBy = author, CreatedOn = utc.AddDays(-5) },
            new Announcement { Title = "Annual Day Celebration", Content = "Join us for the annual day celebration on the last Friday of this month.", Category = "Events", Priority = "Normal", IsActive = true, CreatedById = author.Id, CreatedBy = author, CreatedOn = utc.AddDays(-2) }
        );
        await db.SaveChangesAsync();
        return r with { Announcements = r.Announcements + 2 };
    }

    // ------------------------------------------------------------------
    // Knowledge base articles.
    // ------------------------------------------------------------------
    private static async Task<SeedReport> SeedKnowledgeBaseAsync(AppDbContext db, SeedReport r, DateTime utc)
    {
        if (await db.KnowledgeBaseArticles.AnyAsync()) return r;

        var author = await db.Employees.OrderBy(e => e.Id).FirstOrDefaultAsync();
        if (author == null) return r;

        db.KnowledgeBaseArticles.AddRange(
            new KnowledgeBaseArticle { Title = "How to apply for leave", Content = "Go to Apply Leave, pick dates and submit. Your manager approves in the Review inbox.", Category = "FAQ", Tags = "leave", IsPublished = true, CreatedById = author.Id, CreatedBy = author, CreatedOn = utc, UpdatedOn = utc },
            new KnowledgeBaseArticle { Title = "Password reset guide", Content = "Use 'Forgot password' on the login screen to receive a reset link.", Category = "Guide", Tags = "account", IsPublished = true, CreatedById = author.Id, CreatedBy = author, CreatedOn = utc, UpdatedOn = utc }
        );
        await db.SaveChangesAsync();
        return r with { Articles = r.Articles + 2 };
    }

    // ------------------------------------------------------------------
    // Holidays for the current calendar year.
    // ------------------------------------------------------------------
    private static async Task<SeedReport> SeedHolidaysAsync(AppDbContext db, SeedReport r, DateOnly today)
    {
        var year = today.Year;
        if (await db.Holidays.AnyAsync(h => h.Date.Year == year)) return r;

        var holidays = new[]
        {
            new Holiday { Name = "Republic Day", Date = new DateOnly(year, 1, 26), Type = "Fixed" },
            new Holiday { Name = "Independence Day", Date = new DateOnly(year, 8, 15), Type = "Fixed" },
            new Holiday { Name = "Gandhi Jayanti", Date = new DateOnly(year, 10, 2), Type = "Fixed" },
            new Holiday { Name = "Diwali", Date = new DateOnly(year, 11, 10), Type = "Fixed" },
            new Holiday { Name = "Christmas", Date = new DateOnly(year, 12, 25), Type = "Fixed" },
            new Holiday { Name = "Holi", Date = new DateOnly(year, 3, 6), Type = "Optional" }
        };
        db.Holidays.AddRange(holidays);
        await db.SaveChangesAsync();
        return r with { Holidays = r.Holidays + holidays.Length };
    }

    // ------------------------------------------------------------------
    // Attendance records for the last two weeks.
    // ------------------------------------------------------------------
    private static async Task<SeedReport> SeedAttendanceAsync(AppDbContext db, SeedReport r, DateTime utc, DateOnly today)
    {
        if (await db.AttendanceRecords.AnyAsync()) return r;

        var employees = await db.Employees.Where(e => e.Status == "Active" || e.Status == "Onboarding" || e.Status == null).Select(e => e.Id).ToListAsync();
        var start = DateTime.UtcNow.Date.AddDays(-10);
        var added = 0;
        for (var i = 0; i < 10 && added < 200; i++)
        {
            var day = start.AddDays(i);
            if (day.DayOfWeek == DayOfWeek.Saturday || day.DayOfWeek == DayOfWeek.Sunday) continue;
            foreach (var employeeId in employees)
            {
                if (added >= 200) break;
                var clockIn = day.AddHours(9).AddMinutes(10);
                var clockOut = day.AddHours(18).AddMinutes(15);
                db.AttendanceRecords.Add(new AttendanceRecord
                {
                    EmployeeId = employeeId,
                    Date = day,
                    ClockIn = clockIn,
                    ClockOut = clockOut,
                    Status = "Present",
                    Notes = "Demo seeded attendance",
                    CreatedOn = utc
                });
                added++;
            }
        }
        await db.SaveChangesAsync();
        return r with { Attendance = r.Attendance + added };
    }

    // ------------------------------------------------------------------
    // Timesheets.
    // ------------------------------------------------------------------
    private static async Task<SeedReport> SeedTimesheetsAsync(AppDbContext db, SeedReport r, DateTime utc, DateOnly today)
    {
        if (await db.TimesheetEntries.AnyAsync()) return r;

        var project = await db.Projects.FirstOrDefaultAsync();
        var employeeIds = await db.Employees.Where(e => e.Status == "Active" || e.Status == "Onboarding" || e.Status == null).Select(e => e.Id).ToListAsync();
        var added = 0;
        foreach (var employeeId in employeeIds)
        {
            for (var i = 1; i <= 5 && added < 60; i++)
            {
                db.TimesheetEntries.Add(new TimesheetEntry
                {
                    EmployeeId = employeeId,
                    ProjectId = project?.Id,
                    Date = utc.AddDays(-i).Date,
                    Hours = 8,
                    Description = "Feature development and code review",
                    Category = "Development",
                    Status = "Approved",
                    ApprovedById = 1,
                    ApprovedOn = utc,
                    CreatedOn = utc
                });
                added++;
            }
        }
        await db.SaveChangesAsync();
        return r with { Timesheets = r.Timesheets + added };
    }

    // ------------------------------------------------------------------
    // Salary discussions.
    // ------------------------------------------------------------------
    private static async Task<SeedReport> SeedSalaryDiscussionsAsync(AppDbContext db, SeedReport r, DateTime utc)
    {
        if (await db.SalaryDiscussions.AnyAsync()) return r;

        var proposer = await db.Employees.OrderBy(e => e.Id).FirstOrDefaultAsync();
        var target = await db.Employees.Where(e => e.Id == 3 || e.Id == 7).ToListAsync();
        foreach (var emp in target)
        {
            if (proposer == null) continue;
            db.SalaryDiscussions.Add(new SalaryDiscussion
            {
                EmployeeId = emp.Id,
                ProposedSalary = 65000m + emp.Id * 1000m,
                ApprovedSalary = emp.Id == 3 ? 66000m : null,
                Status = emp.Id == 3 ? "Approved" : "Proposed",
                ProposedById = proposer.Id,
                ApprovedById = emp.Id == 3 ? proposer.Id : null,
                DiscussionDate = utc.AddDays(-7),
                Notes = "Annual review discussion.",
                CreatedOn = utc
            });
            await db.SaveChangesAsync();
            r = r with { Discussions = r.Discussions + 1 };
        }
        return r;
    }

    // ------------------------------------------------------------------
    // Leave encashments.
    // ------------------------------------------------------------------
    private static async Task<SeedReport> SeedEncashmentsAsync(AppDbContext db, SeedReport r, DateTime utc)
    {
        if (await db.LeaveEncashments.AnyAsync()) return r;

        var leaveType = await db.LeaveTypes.FirstOrDefaultAsync();
        var employee = await db.Employees.Where(e => e.Id == 3).FirstOrDefaultAsync();
        if (leaveType == null || employee == null) return r;

        db.LeaveEncashments.AddRange(
            new LeaveEncashment { EmployeeId = 3, LeaveTypeId = leaveType.Id, DaysRequested = 2, RatePerDay = 2000m, Amount = 4000m, Reason = "Unused balance at year end", Status = "Pending", CreatedOn = utc.AddDays(-3) },
            new LeaveEncashment { EmployeeId = 3, LeaveTypeId = leaveType.Id, DaysRequested = 1, RatePerDay = 2000m, Amount = 2000m, Reason = "Personal planning", Status = "Approved", ApprovedOn = utc.AddDays(-10), ApprovedById = 1, CreatedOn = utc.AddDays(-12) }
        );
        await db.SaveChangesAsync();
        return r with { Encashments = r.Encashments + 2 };
    }

    // ------------------------------------------------------------------
    // Attendance regularizations.
    // ------------------------------------------------------------------
    private static async Task<SeedReport> SeedRegularizationsAsync(AppDbContext db, SeedReport r, DateTime utc, DateOnly today)
    {
        if (await db.AttendanceRegularizations.AnyAsync()) return r;

        var emp = await db.Employees.Where(e => e.Id == 3).FirstOrDefaultAsync();
        var attendance = await db.AttendanceRecords.Where(a => a.EmployeeId == 3).OrderBy(a => a.Date).FirstOrDefaultAsync();
        if (emp == null || attendance == null) return r;

        db.AttendanceRegularizations.Add(new AttendanceRegularization
        {
            EmployeeId = 3,
            AttendanceRecordId = attendance.Id,
            RequestType = "LateArrival",
            Reason = "Train delay.",
            Status = "Pending",
            CreatedOn = utc.AddDays(-1)
        });
        await db.SaveChangesAsync();
        return r with { Regularizations = r.Regularizations + 1 };
    }

    // ------------------------------------------------------------------
    // One offboarding in progress.
    // ------------------------------------------------------------------
    private static async Task<SeedReport> SeedOffboardingAsync(AppDbContext db, SeedReport r, DateTime utc)
    {
        if (await db.EmployeeOffboardings.AnyAsync(o => o.Status == "InProgress")) return r;

        var emp = await db.Employees.Where(e => e.Id == 10).FirstOrDefaultAsync();
        if (emp == null) return r;

        db.EmployeeOffboardings.Add(new EmployeeOffboarding
        {
            EmployeeId = 10,
            Status = "InProgress",
            ResignationDate = utc.AddDays(-2),
            LastWorkingDay = utc.AddDays(28),
            Remarks = "Demo offboarding for handover walkthrough."
        });
        await db.SaveChangesAsync();
        return r with { Offboardings = r.Offboardings + 1 };
    }

    // ------------------------------------------------------------------
    // Visitors.
    // ------------------------------------------------------------------
    private static async Task<SeedReport> SeedVisitorsAsync(AppDbContext db, SeedReport r, DateTime utc, DateOnly today)
    {
        if (await db.Visitors.AnyAsync()) return r;

        var host = await db.Employees.OrderBy(e => e.Id).FirstOrDefaultAsync();
        db.Visitors.AddRange(
            new Visitor { FullName = "Amit Contractor", Email = "amit@vendor.com", Phone = "9876500001", Company = "Vendor Solutions", VisitingEmployee = "Preeti Patil", Purpose = "Project review", ExpectedDate = utc.Date, ExpectedTime = new TimeSpan(11, 0, 0), Status = "CheckedIn", CheckInTime = utc.Date.AddHours(11), HostEmployeeId = host?.Id, Notes = "Demo visitor" },
            new Visitor { FullName = "Sneha Sharma", Email = "sneha@client.com", Phone = "9876500002", Company = "Client Corp", VisitingEmployee = "Rakesh Patil", Purpose = "Client meeting", ExpectedDate = utc.Date.AddDays(1), ExpectedTime = new TimeSpan(15, 0, 0), Status = "Expected", HostEmployeeId = host?.Id, Notes = "Demo visitor" }
        );
        await db.SaveChangesAsync();
        return r with { Visitors = r.Visitors + 2 };
    }
}